### ISSUE TITLE
Implement separate Blog Section 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#12]
Implement blog section in design of page with
- white background section
- grayish background (as now is good)
- corners (no round edges as this is not according to design specs)
- links in red

**Comment by codethejason** [comment]
@mariobehling Would you like it in the same location?

**Comment by mariobehling** [comment]
@codethejason I added a section. Please add it in there. Cheers!

![screenshot from 2016-01-25 17 44 11](https://cloud.githubusercontent.com/assets/1583873/12557496/5a4c636a-c38b-11e5-95f4-8ec418af62ad.png)

**Comment by mariobehling** [comment]
@codethejason Excellent work. At the moment we depend on Yahoo for showing blog content. I wonder if there was a solution to implement it without a third party service, e.g. we could also check if we could add a module to the Drupal blog in order to offer content in another format.

**Comment by mariobehling** [comment]
Please change "See more at FOSSASIA" on the bottom to "Read more in the blog".

**Comment by codethejason** [comment]
@mariobehling I looked into it and offering a JSON format or disabling the same origin policy in the CORS header (which wouldn't be the best idea) could let us automatically parse the data without relying on Yahoo.

**Comment by mariobehling** [comment]
Ok, if you have time to look into how to offer JSON from a Drupal blog would be great. Maybe this is the solution.

**Comment by yasoob** [comment]
IMO we should just display the blog-post titles and not the full content in this section. And then add a hyperlink to the title which leads to the blog-post. The current version does not go along well with the design of the website. What do you say?

**Comment by mariobehling** [comment]
@yasoob I think it is ok for now. We can have a fresh look in a few days. Would be great, to find an existing Drupal theme for the blog, that matches the design of the main page.

**Comment by mariobehling** [comment]
Check out this issue: https://github.com/fossasia/blog.fossasia.org/issues/1
