### ISSUE TITLE
Add links to blog section and expand length of section to include more content

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#146]
* Add links to author, title should link to post
* Expand height of section

**Comment by championshuttler** [comment]
Can you please elaborate this issue @mariobehling . I want to work on it

**Comment by mariobehling** [comment]
@championshuttler 

The section is on the page:
![screenshot from 2017-09-05 13-50-32](https://user-images.githubusercontent.com/1583873/30059880-40a8e024-9241-11e7-8a1d-cbce705f26ba.png)

* Add links to author, title should link to post
* Expand height of section

**Comment by nikssardana** [comment]
Hi
I would like to work on this issue. Can anyone guide me about which files need to be changed?
Also, what should be the new height of the carousel?

**Comment by isuruAb** [comment]
Hi @nikssardana  ,

Please go through the js files of repo.you can change this section ,
https://github.com/fossasia/fossasia.org/blob/gh-pages/js/blog.js
happy coding 👍 

and please check whether @championshuttler  is still working on this issue or not.

**Comment by nikssardana** [comment]
Thanks @isuruAb. I'll look into it.
@championshuttler please reply if you're already working on it, I'll find something else to work on if you've started working on it. Otherwise, I'd like to be assigned to this.

**Comment by nikssardana** [comment]
The xml feed used in the above mentioned file contains link to the blog and author's name, but I could not find the link to author's profile. Where can I find it?

**Comment by isuruAb** [comment]
make this kind of url using author name 
https://blog.fossasia.org/author/mario-behling/

**Comment by championshuttler** [comment]
@nikssardana i am working and i will let you if i won''t be able to do it.
thank you

**Comment by kartiktyagi4282** [comment]
Hi @mariobehling @isuruAb 
Sir, can i fix this bug.I think i have got the solution to this problem.

**Comment by pandyamarut** [comment]
Is this issue still unsolved? if so, please tell me i'll go forward with it. 
Thank you!

**Comment by mariobehling** [comment]
Working at the moment.
