### ISSUE TITLE
width of team member images are differ 

### ISSUE THREAD

**Issue by isuruAb** [fossasia/fossasia.org#148]
width of team member images are differ in small screen sizes.
<img width="567" alt="screen shot 2017-09-04 at 7 56 48 am" src="https://user-images.githubusercontent.com/7692626/30009555-f873cf44-9146-11e7-8a45-c77ad40348ff.png">
<img width="468" alt="screen shot 2017-09-04 at 7 57 20 am" src="https://user-images.githubusercontent.com/7692626/30009574-0e8e4a98-9147-11e7-9a43-108c4783c311.png">

**Comment by sounak98** [comment]
I would like to work on this.

**Comment by mittalprince** [comment]
is this issue has been solved or not . @sounak98

**Comment by sounak98** [comment]
@mittalprince this issue was still there when I had started working on it.
