### ISSUE TITLE
Fix and enhance tweet section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#149]
Currently the tweet section shows some tweets of FOSSASIA accounts that are not related to FOSSASIA. Please implement as follows show tweets and retweets of the following accounts:
* https://twitter.com/fossasia
* https://twitter.com/fasblg
* https://twitter.com/fa_voc
* https://twitter.com/fossasiasg

Also ensure the date of the tweets are shown correctly and instead 0 days ago e.g. 5 hours ago.

![screenshot from 2017-09-06 12-28-48](https://user-images.githubusercontent.com/1583873/30107686-ccc771ba-92ff-11e7-99eb-a535e679a6c8.png)

**Comment by dilpreetsio** [comment]
@mariobehling I'm having a look at it.

**Comment by singhpratyush** [comment]
@geekyd: Try this request - 

https://api.loklak.org/api/search.json?callback=loklakFetcher.handleData&q=from:fossasia%20OR%20from:fasblg%20OR%20from:fa_voc%20OR%20from:fossasiasg&count=3&source=all&timezoneOffset=-330&minified=true

* Query is `from:account1 OR from:account2 OR ...`
* Set source to all
* No need for `fields` and `limit`
* Go with better timezoneOffset than `0` (see api.loklak.org for example on how to get timezone offset).
