### ISSUE TITLE
Top bar has a moving effect - avoid that effect

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#152]
When a user scrolls down the top and the bar switches to white a moving effect appears when the user scrolls over an item. 

Expected: The underline effect should appear, but the moving effect should not appear.

![screenshot from 2017-09-08 10-18-42](https://user-images.githubusercontent.com/1583873/30202731-bac89d00-947f-11e7-8898-9078471252b2.png)

**Comment by AshishkrGoyal** [comment]
@mariobehling Sir...
can i work on this ??

**Comment by dilpreetsio** [comment]
@AshishkrGoyal Please go ahead!

**Comment by AshishkrGoyal** [comment]
@mariobehling @geekyd 
i have done changes for 2018 summit website, same will be applicable here,
please give a review to changes then i will send i PR for this.
link is:

http://www.ashishkrgoyal.me/2018.fossasia.org/ 

Thanks :smile:

**Comment by dilpreetsio** [comment]
@AshishkrGoyal Thanks for the fix. Please open a PR if you have resolved the issue. All the reviews and changes can be suggested on the PR itself.

**Comment by AshishkrGoyal** [comment]
@geekyd 
please visit this link and review PR.

https://github.com/fossasia/fossasia.org/pull/156

Thanks 😄
