### ISSUE TITLE
Move http content to https

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#153]
There are some issues when switching the http websites to https, e.g. we have some scripts that are using http.

Please go through the website with issues, propose and implement solutions, e.g.
https://events.fossasia.org/ -> https://github.com/fossasia/events.fossasia.org
https://2018.fossasia.org/ -> https://github.com/fossasia/2018.fossasia.org
https://2017.fossasia.org/ -> https://github.com/fossasia/2017.fossasia.org
https://2016.fossasia.org/ -> https://github.com/fossasia/2016.fossasia.org
https://2015.fossasia.org/ -> https://github.com/fossasia/2015.fossasia.org

![screenshot from 2017-09-08 12-38-00](https://user-images.githubusercontent.com/1583873/30208178-94d1dde2-9492-11e7-93cb-a73ab4ff291a.png)

**Comment by venkateshdb** [comment]
I think there is only problem with 2018.fossasia.org.

after some editing.
now@ https://venkateshbellale.github.io/2018.fossasia.org/

**Comment by isuruAb** [comment]
@venkateshbellale  please send a pull request to this issue. 
https://github.com/fossasia/2018.fossasia.org/issues/34

**Comment by dilpreetsio** [comment]
@venkateshbellale This issue is resolved in https://github.com/fossasia/2018.fossasia.org/pull/32
You can take up these issue I just opened:
https://github.com/fossasia/events.fossasia.org/issues/6
https://github.com/fossasia/events.fossasia.org/issues/7
https://github.com/fossasia/2016.fossasia.org/issues/113
https://github.com/fossasia/2015.fossasia.org/issues/48
https://github.com/fossasia/2017.fossasia.org/issues/68

**Comment by harshit98** [comment]
@geekyd I am still able to see this issue on <a href="2018.fossasia.org">2018.fossasia.org</a>

![capture](https://user-images.githubusercontent.com/22245418/30240366-dc0abd14-958c-11e7-9397-28b6953e928c.PNG)

**Comment by nzec** [comment]
Aren't all the websites using https already? I do not see a single script/resource on any of these websites using http.

**Comment by Ploypiti** [comment]
The https loaded just fine but I got this error (except 2018 site no error detected).

![error](https://user-images.githubusercontent.com/32614202/34077648-67a56c10-e33b-11e7-8cd4-07dd61783e62.jpg)

**Comment by 0x48piraj** [comment]
I understood what you're saying @mariobehling :heart: 
I am starting to resolve this issue.
**It's a huge issue, so it will take some time.** _(If any member wants to work, say before firing a PR :smile: )_
Also, you can remove https://2018.fossasia.org/  as it is working just fine! :+1:

**Comment by 0x48piraj** [comment]
This preview will help knowing the actual issue. :smile: 
![image](https://user-images.githubusercontent.com/5800726/34078010-ab7c9cf0-e337-11e7-9e35-4dd04d734c45.png)

> @mariobehling we can add this screenshot.
