### ISSUE TITLE
Arrow controllers are not working

### ISSUE THREAD

**Issue by isuruAb** [fossasia/fossasia.org#154]
Arrow controllers of blog section are not working correctly.

<img width="1006" alt="screen shot 2017-09-08 at 8 25 27 pm" src="https://user-images.githubusercontent.com/7692626/30217542-1198e622-94d4-11e7-9268-842c5e20cc3d.png">

**Comment by mittalprince** [comment]
sir may i work on this issue ?

**Comment by isuruAb** [comment]
@mittalprince  yes you can proceed with this

**Comment by mittalprince** [comment]
sir actually i'm new in this field so please would you guide me , what steps should i follow to solve this issue

**Comment by mittalprince** [comment]
sir one more thing that there is no arrow visible in blog section, please help me  @isuruAb 
thanks

**Comment by isuruAb** [comment]
hi @mittalprince ,
this is the place you need to edit. 
https://github.com/fossasia/fossasia.org/blob/gh-pages/js/blog.js
now you have to go through the code and check the issue. then send a PR with new solution.

happy coding 👍

**Comment by mittalprince** [comment]
thanks sir 
i will see it and try my best to solve it

**Comment by AshishkrGoyal** [comment]
@isuruAb 
next and prev both button are working properly.
please view this issue once 

thanks

**Comment by isuruAb** [comment]
@AshishkrGoyal  could you please tell me  what is the browser you are using ?

**Comment by AshishkrGoyal** [comment]
@isuruAb 
Google Chrome | 60.0.3112.113 (Official Build) (64-bit) (cohort: Stable)
-- | --

**Comment by Nshul** [comment]
This issue persists on firefox but not on chrome.
Can i work on this issue if it hasn't been resolved yet?
@isuruAb

**Comment by AshishkrGoyal** [comment]
@Nshul 
sure you can solve it.. 
go ahead 😄 
cheers 👍

**Comment by isuruAb** [comment]
@Nshul  please go ahead 👍

**Comment by Nshul** [comment]
@isuruAb Can you please help me out here

I tried modifying the blog.js file at https://github.com/fossasia/fossasia.org/blob/gh-pages/js/blog.js
with these three functions for manual movement of carousel.
Apparently, the log function works i.e. the arrow clicks are detected but the carousel doesnt goto next or prev 
```javascript
$(document).ready(function() {
    
    var url = 'http://blog.fossasia.org/feed/?format=xml';
    feeds(url);

    $(".carousel").carousel({
        interval:2000
    });
```
```javascript
    // $(".carousel-control.left").click(function () {
    //     console.log("left click detected");
    //     $("#myCarousel").carousel("prev");
    // });
    //
    // $(".carousel-control.right").click(function () {
    //     console.log("Right click detected");
    //     $("#myCarousel").carousel("next");
    // });
```
```javascript
    // $('.carousel-control.left').click(function(e) {
    //     console.log("left click detected");
    //     e.stopPropagation();
    //     $('#myCarousel').carousel('prev');
    //     return false;
    // });
    // $('.carousel-control.right').click(function(e) {
    //     console.log("Right click detected");
    //     e.stopPropagation();
    //     $('#myCarousel').carousel('next');
    //     return false;
    // });
```
```javascript
    // $('a[data-slide="prev"]').click(function() {
    //     console.log("left click detected");
    //     $('#myCarousel').carousel('prev');
    // });
    //
    // $('a[data-slide="next"]').click(function() {
    //     console.log("Right click detected");
    //     $('#myCarousel').carousel('next');
    // });
 });
```
But sadly,the issue still persists


I even tried to modify the index.html at https://github.com/fossasia/fossasia.org/blob/58d9e46375d688e1edca1d0c04ce3db56c8957d8/index.html#L648 to change the
```javascript
left carousel-control
```
to

```javascript
carousel-control-prev
```

and

https://github.com/fossasia/fossasia.org/blob/58d9e46375d688e1edca1d0c04ce3db56c8957d8/js/blog.js#L25
here from
```javascript
<div class='item active'>
```
to
```javascript
<div class='carousel-item active'>
```
according to the official documentation of Bootstrap v4
but then
![screenshot from 2017-09-25 22-09-30](https://user-images.githubusercontent.com/26252118/30820570-c899b17c-a211-11e7-8db3-f0b60fd69731.png)
this happens

Loading the xml content takes a lot of time. I dont know why this happens. Often there is a 500 error from server regarding the xml data.

Could you please give me a little direction?
Thank you

**Comment by mariobehling** [comment]
Working now.
