### ISSUE TITLE
URL changes when user clicked on the featured images of blog posts

### ISSUE THREAD

**Issue by nanspro** [fossasia/fossasia.org#155]
![workspace 1_001](https://user-images.githubusercontent.com/24641089/30223948-7af2e094-94ea-11e7-86a6-ae67df60a036.png)
![workspace 1_002](https://user-images.githubusercontent.com/24641089/30223951-7e29cb9c-94ea-11e7-9d68-b6ed455c79fd.png)

**Comment by nanspro** [comment]
@isuruAb  Can you tell me what it should do when it gets clicked

**Comment by isuruAb** [comment]
Hi @nanspro ,
Actually you can't change these things here, because blog is separate wordpress site. If you need to change this you have to edit the wordpress theme.
@mariobehling  need your opinion here.

**Comment by mariobehling** [comment]
This is normal behavior of Wordpress and not a bug.
