### ISSUE TITLE
Responsiveness issue:design and alignment of input boxes is not good for all devices

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/fossasia.org#158]
@mariobehling @isuruAb @niccokunzmann 
Screenshot 
alignment of input boxes is good for devices whose width > 770px but devices less than this width have to face alignment issue of input box which spoil the UI and UX.

like in this screenshot all the three boxes are not aligned centered or aside, while all have their different alignment.

![image](https://user-images.githubusercontent.com/25322851/30246554-48d3560c-961b-11e7-81eb-914d6dda2422.png)

Thanks 👍

**Comment by mani87** [comment]
@AshishkrGoyal i want to work on this. Can i?

**Comment by AshishkrGoyal** [comment]
@mani87 
actually i am working on this 😄 

Thanks 👍

**Comment by mani87** [comment]
OK @AshishkrGoyal  :)

Thankyou!

**Comment by mariobehling** [comment]
This seems to have been solved already. If anything is unclear, please reopen new issue.
