### ISSUE TITLE
carousel images cut problem:responsiveness issue

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/fossasia.org#159]
@isuruAb @niccokunzmann 
images come in full size while working with large devices but with small devices image is not coming with proper dimensions.

**Screenshot for small devices:**

![image](https://user-images.githubusercontent.com/25322851/30246585-707bad66-961c-11e7-835e-813f246ae854.png)

**Screenshot for large devices:**

![image](https://user-images.githubusercontent.com/25322851/30246594-a409d2ca-961c-11e7-9e35-c5789fb4293b.png)

Thanks 👍

**Comment by AshishkrGoyal** [comment]
@isuruAb 
i am working for this issue 

Thanks 👍

**Comment by isuruAb** [comment]
hi @AshishkrGoyal , but it is better if you can work on major projects instead of minor bugs of fossasia website. try to work on other major projects like susi, loklak or open event.
happy coding 👍

**Comment by AshishkrGoyal** [comment]
@isuruAb 
i am new to open source contribution field and want to be a developer for fossasia organization because i have interest in fossasia's projects..

i think that may be at this time it is hard to contribute major projects but gradually i will move to major projects..

can you please guide me that i am going in right direction or it is wrong track??

i will be highly grateful to you for the same 😄 

Thanks 😄

**Comment by sansyrox** [comment]
@AshishkrGoyal can i work on this issue?

**Comment by AshishkrGoyal** [comment]
@stealthanthrax 
i am working for this issue already 😄

**Comment by mariobehling** [comment]
I don't really see this as a bug and I don't know what should be improved. The current way it works is good for me. It does not make sense to work on these small things. We need urgent help with Open Event, SUSI.AI, Yaydoc, loklak, phimpme, PSLab. These kind of issues here are taking away time of reviewers and mentors. Therefore I am closing this issue. Please help to develop actual software in FOSSASIA if you are interested to contribute.
