### ISSUE TITLE
Unnecessary White Space 

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/fossasia.org#162]
In the FOSSASIA team page, there is an unnecessary white space between two images. https://fossasia.org/team
![bug](https://user-images.githubusercontent.com/15213246/30281935-6432963a-9731-11e7-93ce-4e4cd70e9066.png)

**Comment by isuruAb** [comment]
in chrome it works fine. are you working on this issue ?

**Comment by meets2tarun** [comment]
Yes, it works perfectly in Chrome but one can reproduce the issue in Firefox.
I would like to solve this issue.

**Comment by Pk13055** [comment]
Can you post a screenshot here?

**Comment by meets2tarun** [comment]
> Can you post a screenshot here?

It is above there.

**Comment by mariobehling** [comment]
Reason is probably an image which does not have the exact size.

**Comment by Pk13055** [comment]
Could we possibly use flexboxes for the images to render properly across browsers/versions?

**Comment by mariobehling** [comment]
The best is: Avoid a discussion that could take hours, if you could solve the issue in just a few minutes.

**Comment by AshishkrGoyal** [comment]
@mariobehling sir.
i think there is no issue like that now..
so please close this issue 😄
