### ISSUE TITLE
Add bottom text, address and Github icon

### ISSUE THREAD

**Issue by techyay** [fossasia/fossasia.org#168]
Please do the following changes on all pages:
* On the top right of the menu add a Github icon and link to https://github.com/fossasia
* On the footer change the FOSSASIA text as follows:
>  About FOSSASIA
FOSSASIA develops Open Source software and hardware solutions with a global developer community from its base in Asia and organizes Open Technology events around the year. The organization runs coding programs and development contests. The annual FOSSASIA Summit is the premier Open Technology event in Asia for developers, contributors, start-ups, and technology companies. FOSSASIA was founded in 2009 by Mario Behling and Hong Phuc Dang.

* On the footer change the address to: 
> Ms. DANG Hong Phuc
FOSSASIA
6 Eu Tong Sen Street, #05-07 The Central, Singapore 059817

**Comment by Pk13055** [comment]
I will work on this!

**Comment by Pk13055** [comment]
@techyay There is no _github icon_ in the icon css that is used. What should I use instead?

**Comment by mariobehling** [comment]
Look there is a github icon on the bottom of the page, through in black. Please check what options are there and find a way to add an icon.

**Comment by Pk13055** [comment]
@mariobehling I shall check it out. In the meanwhile, can you review the other changes? 
EDIT: I have added the icon from `font-awesome` itself.

**Comment by mariobehling** [comment]
1. On the top right of the menu add a Github icon and link to https://github.com/fossasia

2. On the Footer Address "FOSSASIA" is missing. The address should be added after "FOSSASIA".
* FOSSASIA
> Ms. DANG Hong Phuc
FOSSASIA
6 Eu Tong Sen Street, #05-07 The Central, Singapore 059817

**Comment by Pk13055** [comment]
@mariobehling Can you check out #170, the comments that I've added?

**Comment by sagar-kalra** [comment]
I would like to work on this issue. @mariobehling

**Comment by sagar-kalra** [comment]
Submitted a PR https://github.com/fossasia/fossasia.org/pull/175

**Comment by Pk13055** [comment]
It's good to see your interest in this issue. But next time on, claim
issues that haven't been claimed already.

**Comment by sagar-kalra** [comment]
Well, sorry for that. I ll keep this in mind next time I'll work on an issue.
