### ISSUE TITLE
Sudden gap between elements in the core developers section

### ISSUE THREAD

**Issue by anshulwadhawan** [fossasia/fossasia.org#188]
@mariobehling 
![issue](https://user-images.githubusercontent.com/25061477/31053741-d079295e-a6c1-11e7-922e-f0a6fac46c61.png)

I am interested to work on this issue.

**Comment by anshulwadhawan** [comment]
@mariobehling 
Please refer to my PR-https://github.com/fossasia/fossasia.org/pull/189
I have fixed this issue.

**Comment by AshishkrGoyal** [comment]
@anshulwadhawan it is good that you first open the issue and then by asking for working on it, send PR for it,
definitely it is good that you are working for it but following best practices will increase value of your contribution 😄 

Thanks 👍 
Happy Coding 😄

**Comment by anshulwadhawan** [comment]
@AshishkrGoyal 
Sure sir.
I will take care from now onwards.

**Comment by mariobehling** [comment]
Seems solved.
