### ISSUE TITLE
Slower Blog post transitions

### ISSUE THREAD

**Issue by shivamMg** [fossasia/fossasia.org#19]
Reading the preview blog posts at front page is difficult. The transitions are very fast. <del>They should stop on mouse hover.</del>

<del>"Read more in the blog" button shouldn't be full-width on larger devices.</del>

If someone gives a go ahead, I would like to work on this one.

**Comment by jigyasa-grover** [comment]
You can send in your improvements ...

**Comment by shivamMg** [comment]
Thank you @jig08. I'll submit a PR as soon as I can.

**Comment by shivamMg** [comment]
@jig08 I've solved the issue in https://github.com/fossasia/fossasia.org/pull/20
I didn't include changes for the stop-at-mouse-over thing. It would have been confusing for the user, since the blog posts don't have a visible border. Also, changing dimensions of the Read more button didn't look neat, so I kept it as it is.

**Comment by jigyasa-grover** [comment]
Okay. Closing this issue with the blog transitions made to `fadeIn` and `fadeOut` instead of abrupt views.
