### ISSUE TITLE
Text flowing out of allotted box

### ISSUE THREAD

**Issue by anshulwadhawan** [fossasia/fossasia.org#193]
Current state:
On viewing the website on Redmi Note 3, the text after the blog posts carousel seems to come out of the allotted space.
Expected state : The text should not overflow out of the grey background and should be properly aligned with respect to the background.

![issue](https://user-images.githubusercontent.com/25061477/31132701-1c911ff8-a87b-11e7-9deb-7e2a5eb9d589.png)

I want to work on this issue.
@mariobehling 
@isuruAb

**Comment by isuruAb** [comment]
@anshulwadhawan  yes you can proceed

**Comment by anshulwadhawan** [comment]
This issue has been solved.
Please have a look at my PR- https://github.com/fossasia/fossasia.org/pull/195
Thanks :)
@isuruAb
