### ISSUE TITLE
Icons in the footer contact us bar overflow

### ISSUE THREAD

**Issue by anshulwadhawan** [fossasia/fossasia.org#194]
Currently:
On viewing the website on Redmi Note 3, the contact us footer bar icons overflow out of the line(to the next line).
Expectation :All the icons should be in the same line.

![issue](https://user-images.githubusercontent.com/25061477/31133043-fcda42f6-a87b-11e7-8da0-7d276a45f167.png)

I want to work on this issue.
@mariobehling 
@isuruAb

**Comment by nzec** [comment]
Will this be worked on? I don't think this is required.

**Comment by ParthS007** [comment]
closing this as no problem in footer 👍
