### ISSUE TITLE
Change footer UI for "Back to Top"

### ISSUE THREAD

**Issue by vanshsoni** [fossasia/fossasia.org#197]
As we can see back to top link is not eye-catching to user, We can change it to back to top button as like in screenshot 1
![screenshot 1](https://user-images.githubusercontent.com/20061884/31539539-769a0106-b026-11e7-8564-dd0fb0518481.png)
![screenshot 74](https://user-images.githubusercontent.com/20061884/31539566-971ee8ba-b026-11e7-833d-8aefe5625bf9.png)

**Comment by jainkeval** [comment]
I would like to work on it.

**Comment by jainkeval** [comment]
![image](https://user-images.githubusercontent.com/26284185/31545846-92fd1780-b03e-11e7-945b-c8604ae3b98b.png)
Is this fine??

**Comment by mariobehling** [comment]
Thanks, but this has low priority. Please help on FOSSASIA's software projects instead. 

Closing it. Cheers.
