### ISSUE TITLE
improvement of UI 

### ISSUE THREAD

**Issue by AshishkrGoyal** [fossasia/fossasia.org#201]
@isuruAb i want to improve UI of this site because this site has many bugs at various screen sizes.
i will send PR for my code to this repository and you are requested to please review it 👍 

can i proceed further please reply sir as soon as possible 😄 
Thanks in advance 👍

**Comment by isuruAb** [comment]
Could you please list down all the bugs that you identified at the moment. Then all others can see those bugs which you are working.

It would be really good if you can work on major projects instead of these web pages.

**Comment by AshishkrGoyal** [comment]
@isuruAb can you please suggest me some projects of fossasia for which i can contribute??
i am JSlover 👍 
really it will be a big help 
Thanks in advance 👍

**Comment by isuruAb** [comment]
@AshishkrGoyal  there are lot of JS projects
https://github.com/fossasia/chat.susi.ai

or just search by language
https://github.com/fossasia?utf8=%E2%9C%93&q=&type=&language=javascript

It is pleasure to help you.
cheers 👍
