### ISSUE TITLE
problem in dropdown menu when we reduce the screen width less then 769px(approx)

### ISSUE THREAD

**Issue by luckykumardev** [fossasia/fossasia.org#202]
dropdowns 
1.PROJECTS
2.EVENTS
not completely visible when we reduce screen width less the 769(approx)
![fossasia 1](https://user-images.githubusercontent.com/32070019/31858809-99aaa890-b6b5-11e7-964c-aab84f6a5742.jpg)
![fossasia 3](https://user-images.githubusercontent.com/32070019/31858811-9e2630d8-b6b5-11e7-8bd0-14ca2c8cebf0.jpg)
![fossasia 2](https://user-images.githubusercontent.com/32070019/31858813-a24f7eb2-b6b5-11e7-9635-337296e70244.png)
![fossasia 4](https://user-images.githubusercontent.com/32070019/31858814-aa23e8e4-b6b5-11e7-83ad-0dc236ba3a5f.png)

can I work on this issue?

**Comment by isuruAb** [comment]
@luckykumardev  yes work on this. if you can work of major projects that would be really great. 👍  cheers

**Comment by luckykumardev** [comment]
thanks @isuruAb I will try.
