### ISSUE TITLE
Get Stripe Credit Card Payments to work on Donate page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#212]
On the donate page Stripe is still set to Demo account (https://fossasia.org/donate.html#stripe). Please propose and make the required changes to get Stripe working.

Relevant documentation is here: https://stripe.com/docs/stripe-js/elements/quickstart

**Comment by nzec** [comment]
Will try to do this. Will be taking at least 2 days.

**Comment by nzec** [comment]
Okay. So @mariobehling you need to generate your own key by signing in. And then you can put it in 
```javascript
var stripe = Stripe('your-key')
```

**Comment by mariobehling** [comment]
The key is already in the code, but there are some other issues:
`input type="hidden" id="pk_live_TYUOty0alel95s5ZGMydBd8Q" value="" name="pk_live_TYUOty0alel95s5ZGMydBd8Q" `

https://github.com/fossasia/fossasia.org/blob/gh-pages/donate.html#L198`

**Comment by nzec** [comment]
@mariobehling Okay. I will see.

**Comment by vaibhavsingh97** [comment]
@duttaditya18 What's the status? Any help needed

**Comment by championpaddler** [comment]
@mariobehling  The Donate Stripe Page is working. Any  Enhancement to be made in it??
