### ISSUE TITLE
Fix blog area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#213]
The blog area has a few issues:
* Add some padding on top and bottom of area
* Add padding on left and right providing some space to edge of area
* Center images
* Ensure going over the link area is clickable. Some area of link areas are not entirely clickable

![screenshot from 2017-12-12 12-16-47](https://user-images.githubusercontent.com/1583873/33881924-b687a5a4-df36-11e7-8968-0663adbe762a.png)

**Comment by nzec** [comment]
On it!
