### ISSUE TITLE
Make social media buttons to share info about FOSSASIA

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#214]
The social media buttons could share info about FOSSASIA. Implement them as popups in the same way as on https://publiccode.asia.
![screenshot from 2017-12-12 12-24-09](https://user-images.githubusercontent.com/1583873/33882149-7a3d01f6-df37-11e7-8ebc-1fd7aad4c47c.png)

**Comment by nzec** [comment]
On it!
