### ISSUE TITLE
Add members and improve team page: Developers, GCI/GSoC mentors, students etc.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#216]
The team page at https://fossasia.org/team is missing team members and missing information including:
* mentors of GCI/GSoC
* GSoC students of 2016 and 2017 into section "Alumni"
* Codeheat finalists into section "Alumni"
* FOSSASIA Summit organizers

**Note**: Only keep people in one category, e.g. if they already show up on the advisory board there is no need to add them again to the event organizer section.

**Comment by ryushar** [comment]
Added about half of GSoC 2017 students, anyone who wishes to take up this issue can continue adding more students after Afroz Ahamad from this page: [https://summerofcode.withgoogle.com/archive/2017/organizations/5936828200779776/](https://summerofcode.withgoogle.com/archive/2017/organizations/5936828200779776/) :tada:

**Comment by nzec** [comment]
@2coolife @mariobehling On it!

**Comment by abishekvashok** [comment]
@mariobehling pls open this as it is not completed yet
