### ISSUE TITLE
Add new menu item: "Contribute", Format code properly,....

### ISSUE THREAD

**Issue by supunTE** [fossasia/fossasia.org#236]
Add a menu item, "Contribute" with links of FOSSASIA's repositories on GitHub for easily make contributors for FOSSASIA.

**Comment by supunTE** [comment]
- Indent codes and use spaces. Remove unwanted spaces.

**Comment by supunTE** [comment]
I am working!

**Comment by mariobehling** [comment]
We already have the info how to contribute in the projects section. Indent code is the only thing we need. Please don't open links in new windows and change the color. We need to align all FOSSASIA subsites now instead of changing styles. Therefore closing it.
