### ISSUE TITLE
Dropdown Menu

### ISSUE THREAD

**Issue by manmeet0307** [fossasia/fossasia.org#240]
![image](https://user-images.githubusercontent.com/32425680/34477437-42b19244-efc0-11e7-92ec-43267067c89b.png)
Extra space in dropmenu should be removed.

**Comment by ParthS007** [comment]
Please update your status.

**Comment by harsh-jindal** [comment]
@ParthS007 Can I work on this issue?

**Comment by ParthS007** [comment]
Yes @harsh-jindal  Please go ahead 👍
