### ISSUE TITLE
Hovering missing in side navigation

### ISSUE THREAD

**Issue by manmeet0307** [fossasia/fossasia.org#241]
In side navigation of fossasia.org hovering of context is missing
![image](https://user-images.githubusercontent.com/32425680/34477631-87e2731e-efc1-11e7-8b3f-b757bf2e24df.png)
After updating it should look like:
![image](https://user-images.githubusercontent.com/32425680/34477670-b84596f8-efc1-11e7-8987-4162b42a5338.png)

**Comment by abishekvashok** [comment]
Please work only after if an admin agrees.
Ping @mariobehling

**Comment by manmeet0307** [comment]
What I  need to do to take the approval @abhishek1995s?
Please guide me I am new to this organisation.

**Comment by mariobehling** [comment]
This feature is currently not needed. We need to align all FOSSASIA sites instead of adding more complexity.

**Comment by manmeet0307** [comment]
I would appreciate if @mariobehling  you may guide me with an issue to which I can contribute.
I am new to open source.This project is appealing me.

**Comment by mariobehling** [comment]
Please contribute in our software projects. There are only small issues in the websites apart from the FOSSASIA Summit site of 2012 and 2014 for example.
