### ISSUE TITLE
Google+ link is missing

### ISSUE THREAD

**Issue by manmeet0307** [fossasia/fossasia.org#242]
The link to google+ of fossasia is missing from both side navigation bar and footer of fossasia.org
![image](https://user-images.githubusercontent.com/32425680/34478084-e66dc9bc-efc4-11e7-8f1e-d9a64cf036e3.png)
After updating it should like:
![image](https://user-images.githubusercontent.com/32425680/34478096-0660c4fe-efc5-11e7-80d9-380676bcdd76.png)

**Comment by shikhar-scs** [comment]
If no one is working on this issue can i please fix it ?

**Comment by manmeet0307** [comment]
I am working on it

**Comment by shikhar-scs** [comment]
ok
