### ISSUE TITLE
Image Slider Next/ Prev button, height changing.

### ISSUE THREAD

**Issue by mithlesh4257** [fossasia/fossasia.org#273]
![screenshot from 2018-01-13 16-44-10](https://user-images.githubusercontent.com/22450186/34903643-beedb7c2-f85b-11e7-9325-b11eb7550749.png)
![screenshot from 2018-01-13 16-44-16](https://user-images.githubusercontent.com/22450186/34903644-bf34628a-f85b-11e7-88fe-f5018f332f4b.png)

See above two image. How height is changing in both cases
or else visit https://fossasia.org/

**Comment by mukesh4601** [comment]
yes sure

**Comment by mukesh4601** [comment]
![screenshot from 2018-01-15 11-38-14](https://user-images.githubusercontent.com/28723602/34929242-a82067c2-f9e8-11e7-86d2-b54e1ea57d49.png)


See Size of Icons Increases
1: Increasing  the Font size of glyphicon icons Will Increase its Height as well .
