### ISSUE TITLE
Add hover property for links in the side menu bar

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/fossasia.org#277]
I'm working on this issue.

**Comment by ghost** [comment]
i m new to git, so please can you explain what does "#277" mean?

**Comment by harsh-jindal** [comment]
@samarth-khajuria I'm almost done with this issue.

**Comment by rupav** [comment]
@samarth-khajuria that's just Issue number. Used so that not needed to post the whole url of the issue. It can be referenced by a number directly.

**Comment by mariobehling** [comment]
Sidebar colors should not be changed.

**Comment by harsh-jindal** [comment]
Okay
