### ISSUE TITLE
Change colour of carousel indicator 

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/fossasia.org#280]
The colour if carousel indicator is white which is not visible because of white background.
Change it's colour.
I'm working on this

**Comment by mariobehling** [comment]
Not sure, what you mean. Do you have a screenshot.

**Comment by harsh-jindal** [comment]
@mariobehling 
Screenshot:-
![screen shot 2018-01-30 at 9 49 22 am](https://user-images.githubusercontent.com/31013104/35548026-cf3067e8-05a2-11e8-9bb8-ce1fdf07551b.png)
In this the middle indicators of the carousel are hidden due to same background colour.
Shall I work  on this?

**Comment by mariobehling** [comment]
I dont think we need middle indicators here. Thank you.
