### ISSUE TITLE
Add the information of members to Team list on FOSSASIA page

### ISSUE THREAD

**Issue by HongKhanhTran** [fossasia/fossasia.org#285]
Please add the information of five members to Team list on FOSSASIA page:
1.	Name: 	   Thanh Tu Dao  
        Position:     Project Consultant 
        Twitter:       https://twitter.com/DaoTuElla
        LinkedIn:     https://www.linkedin.com/in/thi-thanh-tu-dao-b7351616/
        Please add this profile picture:
![ctu-final](https://user-images.githubusercontent.com/36536225/37083249-8e9dbc08-2221-11e8-9449-ff086be92414.jpg)

2.	Name:     Kathy Ho        
        Position:  Community Support Assistant
        Twitter:    https://twitter.com/kathyho31
        LinkedIn: https://www.linkedin.com/in/kathyho31/
        Please add this profile picture:
![mymy-croped](https://user-images.githubusercontent.com/36536225/37075292-c3c076b4-2203-11e8-9168-c210ba9a6f20.jpg)

3.	Name:      Mie Lam
        Position:  Content Writer 
        Twitter:    https://twitter.com/mielamvn
        LinkedIn:  https://www.linkedin.com/in/mie-lam-52153b119/
        Please add this profile picture:
![mie croped](https://user-images.githubusercontent.com/36536225/37075318-e1164a40-2203-11e8-862c-949dbe7f2e4f.jpg)

4.	Name:      Thoai Tran 
        Position:   FOSSASIA Community Outreach
        Twitter:    https://twitter.com/fossasia
        LinkedIn:  https://www.linkedin.com/company/2982840/
        Please add this profile picture:
![thoai-image](https://user-images.githubusercontent.com/36536225/37075330-eee7801c-2203-11e8-98b6-fb826265d18a.png)

5.	Name:      Khanh Tran 
        Position:   Administrative Assistant
        Twitter:    https://twitter.com/tenKhanh
        LinkedIn:  https://www.linkedin.com/in/khanh-tran-b0922ab8/
        Please add this profile picture:
![khanh](https://user-images.githubusercontent.com/36536225/37075342-fc32eed2-2203-11e8-9069-ed91bf16a641.jpg)

Thank you so much!

**Comment by mariobehling** [comment]
Please provide a better picture of Tu Dao.

**Comment by HongKhanhTran** [comment]
@mariobehling I have replaced another one.

**Comment by agarwalaman263** [comment]
@HongKhanhTran 
These names are to be added to which subheadings?

**Comment by HongKhanhTran** [comment]
@cyclopaman please add to Team section. Thank you!
