### ISSUE TITLE
Redirect back to the referrer page after subscribing to news-letter

### ISSUE THREAD

**Issue by sopankhosla** [fossasia/fossasia.org#29]
On clicking 'subscribe' to news-letter, new page `news.fossasia.org/subscribe` is opened. 
IMO it should redirect back to the referring page after about 2 or 3 secs.

**Comment by ashutoshsaboo** [comment]
Umm I have been looking into this. But just an issue. Could you help me out figure, where is the code (as in which HTML file is the code) for `news.fossasia.org` ? @jig08 Could you help me out? @sopu

**Comment by ghost** [comment]
I think this is a seperate service and that's why you can't change the page there. But I'll try to open a new tab with the homepage, before it is going to subscribe.
