### ISSUE TITLE
Move pages to its own folder and change links to css

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#292]
Move the following pages:
* [ ] about.html -> /about/index.html
* [ ] apply.html -> /apply/index.html
* [ ] team.html -> /team/index.html
* [ ] thankyou.html -> /thankyou/index.html
* [ ] mailthanks.html -> /mailthanks/index.html

**Comment by yashLadha** [comment]
Shall I take this up. @mariobehling

**Comment by mariobehling** [comment]
Sure, thanks.

**Comment by mariobehling** [comment]
Also change donate.html. I did not list it, as I missed it, but I hope we can collaborate in a way that if someone misses something the other person will also review items.

**Comment by yashLadha** [comment]
Sure I will add it.

**Comment by mariobehling** [comment]
Same appliest to 
* sitemap.html -> sitemap/index.html
* licenses.htmls -> licenses/index.html

**Comment by yashLadha** [comment]
:+1:
