### ISSUE TITLE
[Meta-Issue] Take out "subscribe" or "Newsletter" from all FOSSASIA Websites and substitute it with the link to main page subscription

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#295]
The subscribe code is on different FOSSASIA Subdomains. This makes the control of the subscription a challenge when the code changes. Substitute all newsletter subscription boxes and take them out of FOSSASIA website. Set any links e.g. in the menu to https://fossasia.org/#subscribe

**Comment by naman653** [comment]
I want to work on the issue. Please assign it to me.
Can you please give me an example of what kind of Subdomains you are talking about.

**Comment by mariobehling** [comment]
We have found another solution where we use a honeypot. Also we need a Recaptcha for the newsletter forms instead. Therefore closing it.
