### ISSUE TITLE
Subscribe link not working in the blog

### ISSUE THREAD

**Issue by SAITARUN55** [fossasia/fossasia.org#298]
![issue298-1](https://user-images.githubusercontent.com/26169081/38860105-0b446df6-424d-11e8-829b-aa39e327773f.PNG)
![Uploading issue298-1.PNG…]()

https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/
while submitting it is showing 404 Not Found Oh dear, this Page is not Available
Please respond to this issue...

**Comment by mariobehling** [comment]
Fixed it. Thanks.
