### ISSUE TITLE
got "404 Not Found" after subscribing mailing list

### ISSUE THREAD

**Issue by noahcse** [fossasia/fossasia.org#299]
I tried to subscribe FOSSASIA newsletter via " https://fossasia.org/#subscribe " / [Subscribe to stay informed](https://fossasia.org/#subscribe) , and I got " https://fossasia.org/mailthanks.html " / [404 Not Found](https://fossasia.org/mailthanks.html)
 after sending my email.

**Comment by mariobehling** [comment]
Changed to http://fossasia.org/mailthanks/

Thanks!
