### ISSUE TITLE
Update foss.vn wiki

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#303]
The FOSS.vn site is a mediawiki. It is currently not loading. Please fix and update the site.

**Comment by satya-vinay** [comment]
FOSS.vn site is loading without any problem.

**Comment by nzec** [comment]
Yup! The FOSS.vn website is loading fine here as well. 

**See this :**

![FOSS.vn](https://i.imgur.com/DwcHVUp.png)

**Comment by mariobehling** [comment]
Thanks. This issue is a reminder for myself to update. Cheers.

**Comment by maxlorenz** [comment]
I upgraded the MediaWiki from 1.23 to 1.30 using the [migration guide](https://www.mediawiki.org/wiki/Manual:Upgrading). Still testing all the plugins but the rest was easy to port

**Comment by maxlorenz** [comment]
this [url](http://foss.vn/index.php?title=%C4%90%E1%BA%B7c_bi%E1%BB%87t:Trang_%C4%91%E1%BA%B7c_bi%E1%BB%87t) is dead
