### ISSUE TITLE
Update Libregraphics.asia

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#304]
The drupal system of Libregraphics.asia on the FOSSASIA server is outdated and needs to be updated.

**Comment by maxlorenz** [comment]
Well the original site threw an error (`Fatal error: Call to undefined function: phptemplate_get_ie_styles()`), which could be fixed using [this forum post](https://www.drupal.org/forum/support/upgrading-drupal/2008-04-08/fatal-error-call-to-undefined-function-phptemplate_get_ie). Now, [libregraphics.asia](http://libregraphics.asia/) shows a generic error message. I am not sure how to proceed here

**Comment by Kreijstal** [comment]
You can try using the debugger to figure out where does the error come from, or ignore it and try exporting it directly from the database.

**Comment by maxlorenz** [comment]
Okay. Going to migrate using a db backup locally and see how that goes
