### ISSUE TITLE
Convert perspektive89 to Wordpress

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#305]
The site on the FOSSASIA server perspektive89.com needs to be converted to Wordpress.

**Comment by Kreijstal** [comment]
The conversion of the images has to be done manually.

**Comment by mariobehling** [comment]
@Kreijstal Ok, how manually? With a script that you start yourself? What is the plan?

**Comment by mariobehling** [comment]
@Kreijstal Looks like users don't appear on the site and were not added: http://perspektive89.com

And some pages were not transferred at all: http://perspektive89.com/2015/12/04/wir-haben-land-schwarze-saat/

**Comment by Kreijstal** [comment]
This might have to do with the script I was using it. 
See https://github.com/jpSimkins/Drupal2WordPress-Plugin/issues/29

About the empty pages, and the users not being imported I'm investigating it.

**Comment by abishekvashok** [comment]
About the empty pages, please convert every special alphabets to ordinary english letters.

**Comment by Kreijstal** [comment]
The idea is that, every image has translation of the tags on very different languages, so you can look up for the images on many languages. You cannot convert these to ASCII. Because it's an international website

**Comment by abishekvashok** [comment]
Not the page title but the page url
