### ISSUE TITLE
Blur images on some parts of website

### ISSUE THREAD

**Issue by itsmylam** [fossasia/fossasia.org#308]
To update the blur images to a clear one from Flickr

**Comment by mariobehling** [comment]
@mielamvn Please point out which images exactly (link and section) and propose an alternative on.

**Comment by itsmylam** [comment]
**Homepage**
1. Banner 1st image: https://flic.kr/p/25p3wZP 
2. Banner 2nd image: https://flic.kr/p/24eZdhF 
3. Section that has "The FOSSASIA Summit is an annual conference...": https://flic.kr/p/249d1gM
4. Section "Subscribe to stay informed": https://flic.kr/p/FPsDKk

**Comment by aditya81070** [comment]
can I take this?

**Comment by meets2tarun** [comment]
@aditya81070 go for it!

**Comment by cweitat** [comment]
@aditya81070 can I know how's the progress for this going?

**Comment by aditya81070** [comment]
@cweitat sorry, I do not noticed this reply. Will work by tomorrow.

**Comment by cweitat** [comment]
@aditya81070 hi! how is it going? do you need help?

**Comment by aditya81070** [comment]
I am doing this now

**Comment by prekshajagetiya123** [comment]
Can I work on this issue?
