### ISSUE TITLE
Location Marker Text not aligned properly.

### ISSUE THREAD

**Issue by soulspark666** [fossasia/fossasia.org#310]
![fossasia page error](https://user-images.githubusercontent.com/37495396/45257641-44dd0780-b3c7-11e8-818a-721550e70b34.png)
Location marker text is not properly aligned on https://fossasia.org/donate/

![corrected fossasia](https://user-images.githubusercontent.com/37495396/45257683-d187c580-b3c7-11e8-8a8d-7da414f4b6a4.png)
It can look like this.

**Comment by samagragupta** [comment]
@soulspark666 @mariobehling   Can I work on it ?
