### ISSUE TITLE
Padding required between text fields and button in subscription form.

### ISSUE THREAD

**Issue by neeraj3029** [fossasia/fossasia.org#312]
**Actual Behaviour**
Padding is not present between text fields and button in subscription form.

![screen shot 2018-09-12 at 3 55 47 pm](https://user-images.githubusercontent.com/31539812/45419251-60386300-b6a4-11e8-857e-656bbd2095b1.png)

**Expected behaviour:**
Padding is required between text fields and button in subscription form.

**Would you like to work on the issue?**
No

**Comment by rohitjain00** [comment]
Can I solve the issue?

**Comment by neeraj3029** [comment]
@rohitjain00 I will be working on this issue.

**Comment by neeraj3029** [comment]
@rohitjain00 I won't be working on this issue now. You can get it assigned.

**Comment by Ridvmodi** [comment]
Can I work on this issue?

**Comment by rohitjain00** [comment]
@Ridvmodi yes just submit a PR

**Comment by Ridvmodi** [comment]
The subscribe form was removed now @rohitjain00

**Comment by siddhantshukla-10** [comment]
Is this issue still open?
If yes, I want to work on it.

**Comment by sahilBhola98** [comment]
can i work on this?

**Comment by Ridvmodi** [comment]
The issue is removed. please close this issue @neeraj3029 .
