### ISSUE TITLE
No uniformity on buttons

### ISSUE THREAD

**Issue by aditya81070** [fossasia/fossasia.org#325]
Problem:- The buttons on [Background and Mission page](https://fossasia.org/about/#background) are not similar.
![screenshot from 2018-09-19 07-53-06](https://user-images.githubusercontent.com/30300772/45727451-6cab4700-bbe1-11e8-9b6c-f29358415e77.png)
![screenshot from 2018-09-19 08-02-04](https://user-images.githubusercontent.com/30300772/45727701-74b7b680-bbe2-11e8-9965-77e4e677bb87.png)

### How to reproduce the bug
Go to [Mission and vision ](https://fossasia.org/about/#background) and in the Contact section. There are two buttons are already red colored and the other one is red on hover.
### Expected Behaviour
Color should be red on hover
### Want to work on the issue?
Yes

**Comment by aditya81070** [comment]
@abishekvashok I am working on this.

**Comment by abishekvashok** [comment]
Alright

**Comment by siddhantshukla-10** [comment]
Sir, I want to work on this.
