### ISSUE TITLE
Add Re-captcha and form validation to subscribe form

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#329]
The subscription form needs the following:
* users should enter both name and email - show an error, if only one is entered
* add re-captcha that opens on pressing "signup" and only submit the email once the captcha is solved

**Comment by amrs-tech** [comment]
I'll try to work on it, sir.

**Comment by amrs-tech** [comment]
I've fixed form validation for subscribing. Please review it. #332

**Comment by Ankurk99** [comment]
For adding Re-captcha I will need to register the website to the Google captcha website, so should I register ?

**Comment by amrs-tech** [comment]
@Ankur99 you can try creating reCAPTCHA on your own instead of going for Google

**Comment by Ankurk99** [comment]
@amrs-tech sorry but I am unable to create reCAPTCHA using PHP or other method so if you want you can take the issue, issue is open.

**Comment by amrs-tech** [comment]
@Ankur99 You can try it. Actually I'm out of resources (laptop) so i want sometime to get back to solve this. :)

**Comment by Ankurk99** [comment]
OK @amrs-tech I will give it a try.

**Comment by Ankurk99** [comment]
For adding Re-captcha I will need to register the site to the Google Re-Captcha website, so should I register ?

**Comment by abishekvashok** [comment]
Yes please

**Comment by kksinghal** [comment]
I am working on this . Pls no one else start to work on this . If anyone is already working . pls confirm .

**Comment by kksinghal** [comment]
@mariobehling I want to confirm if I can use Google recaptcha as this is a open-source org .

**Comment by garvitkhandelwal** [comment]
Is anyone working on this issue? Because I want to work on this.
