### ISSUE TITLE
Review FOSSASIA Team Members and Move Members who haven't contributed for 6 months to Alumni Section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#363]
Many people are contributing to FOSSASIA projects. Who is currently active? Please review FOSSASIA Team Members and Move Members who haven't contributed for 6 months to Alumni Section.

**Comment by sarnava1** [comment]
@mariobehling is this a GCI task?

**Comment by BolajiAyodeji** [comment]
Nice issue @mariobehling

**Comment by mariobehling** [comment]
Yes, you can take this up in GCI. Just look for a suitable task that relates to this.

**Comment by sarnava1** [comment]
@sahilsaha7773 you can look at this task. It is a nice issue.

**Comment by sarnava1** [comment]
> Yes, you can take this up in GCI. Just look for a suitable task that relates to this.

I am actually a CODEHEAT participant and not a GCI participant!

**Comment by mariobehling** [comment]
Anyone can contribute.
