### ISSUE TITLE
Only show team members itself on team photo (no other people)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#368]
Please check team photos and only show team members itself on a photo. If you cannot find a photo with only the team member, delete the photo from the page for now. We will try to come back to it later.

![screenshot from 2018-11-20 02-16-19](https://user-images.githubusercontent.com/1583873/48745155-9ed13780-ec6a-11e8-821a-2c3983f2281b.png)

**Comment by sarnava1** [comment]
@sahilsaha7773 @saarthakchats you can take this up.

**Comment by sahilsaha7773** [comment]
I want to work on this issue
