### ISSUE TITLE
Add related JS on site "adstatus.js"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#373]
The FOSSASIA page processes Googleads js and adstatus.js of doubleclick. Please find out which JS calls these JS and take it out.

![screenshot from 2018-11-23 14-17-03](https://user-images.githubusercontent.com/1583873/48945428-97d84c80-ef2a-11e8-9c3d-560df0a45512.png)

**Comment by supunTE** [comment]
I would like to work on it.
