### ISSUE TITLE
Add screenshots of Android apps into Android section instead of logos

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#374]
The Android App section has logos to link to the app store at the moment. Please add large screenshots here instead.

![screenshot from 2018-11-23 19-17-15](https://user-images.githubusercontent.com/1583873/48956832-7c366b80-ef55-11e8-8ac1-a638f7d73f3e.png)

**Comment by siddharthgusain** [comment]
Please assign this issue to me.

**Comment by mariobehling** [comment]
Please go ahead. Thanks.

**Comment by siddharthgusain** [comment]
Thanks. Working on it. :+1:

**Comment by siddharthgusain** [comment]
@mariobehling  please review . Thanks
