### ISSUE TITLE
The Navigation Bar isn't responsive .

### ISSUE THREAD

**Issue by kksinghal** [fossasia/fossasia.org#386]
While resizing the window , some of the links of the nav-bar comes to the next line  , which looks awful , while the other merges the FOSSASIA logo . 
### Screenshots 
![image](https://user-images.githubusercontent.com/26023139/48968424-a2bbdb80-f015-11e8-9821-158b8945f77e.png)
![image](https://user-images.githubusercontent.com/26023139/48968426-a6e7f900-f015-11e8-9590-a4dac23b41ae.png)

### Would you like to work on the issue ?
Open to all

**Comment by kksinghal** [comment]
@mariobehling Please confirm the relevance of this issue .

**Comment by midhmanohar** [comment]
would like to work on this issue

**Comment by midhmanohar** [comment]
would like to work on this issue

**Comment by AdityaSrivast** [comment]
@KSNINJA Can I work on this issue?

**Comment by kksinghal** [comment]
Yes , It is open to all .

**Comment by garvitkhandelwal** [comment]
I want to work on this issue. I know how it can be solved.

**Comment by Safnaj** [comment]
Is this Issue Fixed ??

**Comment by kshitijk83** [comment]
Can I use Hamburger icon nav bar to make it responsive?

**Comment by abishekvashok** [comment]
There used to be a hamburger but it's not there now. `git blame`
