### ISSUE TITLE
The tweet section is not proper.The link to follow on twitter is hidden by that tweet for some tweets.In short overwriting is taking place

### ISSUE THREAD

**Issue by ghost** [fossasia/fossasia.org#39]
![fossasia1](https://cloud.githubusercontent.com/assets/8669640/16358543/6c58c89e-3b33-11e6-9e6a-99a984f349d5.png)
![fossasia2](https://cloud.githubusercontent.com/assets/8669640/16358551/a0c9371c-3b33-11e6-86f0-4e3358a1924e.png)

**Comment by ghost** [comment]
Can i work on solving this one. I am new to the community and would like to contribute to the community.

**Comment by mananwason** [comment]
@sahilhindwani can you elaborate on what you mean?

**Comment by ghost** [comment]
@mananwason This is a very small problem.As it can be seen in the screenshot attached there is a **follow @fossasia on twitter** line which is overwritten by the tweets.The problem is due to the div size as well as Font is too large to be accommodated in that div size.

**Comment by mariobehling** [comment]
@sahilhindwani Yes, please help. Thank you!
