### ISSUE TITLE
Footer Map Location Text is Inconsistent

### ISSUE THREAD

**Issue by rcya1** [fossasia/fossasia.org#393]
The footer text that says "Ms. DANG Hong Phuc FOSSASIA 6 Eu Tong Sen Street, #5-07 The Central, Singapore 059817" is inconsistent across the pages.

![image](https://user-images.githubusercontent.com/8119928/48972435-57470480-eff8-11e8-80ac-73214d4dfa40.png)
![image](https://user-images.githubusercontent.com/8119928/48972437-5dd57c00-eff8-11e8-86cf-dc4283b95e64.png)
![image](https://user-images.githubusercontent.com/8119928/48972439-63cb5d00-eff8-11e8-93af-eb1caa5a6e1d.png)
![image](https://user-images.githubusercontent.com/8119928/48972440-6928a780-eff8-11e8-9781-24e19370e690.png)

This one is from labs.fossasia.org
![image](https://user-images.githubusercontent.com/8119928/48972444-7cd40e00-eff8-11e8-9e71-e2576bca1f8e.png)
![image](https://user-images.githubusercontent.com/8119928/48972446-8493b280-eff8-11e8-8a6e-4fa8dcf8385a.png)

They should all be made the same. I think that they should all follow the one set in https://labs.fossasia.org/ as it also has a link to openstreetmap.org on it for the location

Open To All

**Comment by siddharthgusain** [comment]
i'm working on this
