### ISSUE TITLE
Unallignment of subscribe div on small devices. 

### ISSUE THREAD

**Issue by siddharthgusain** [fossasia/fossasia.org#395]
![unallign](https://user-images.githubusercontent.com/32402201/48980850-454a8c00-f0f4-11e8-9360-8b71866e387e.png)

**Comment by bansalraghav** [comment]
@siddharthgusain Can I work on this issue?

**Comment by Dharmesh-Poddar** [comment]
I would like to work on it ..

**Comment by siddharthgusain** [comment]
@Dharmesh-Poddar please go ahead . :+1:

**Comment by Dharmesh-Poddar** [comment]
Thanks @siddharthgusain  Looking forward to it..

**Comment by Dharmesh-Poddar** [comment]
please check the pull request #418

**Comment by siddharthgusain** [comment]
@Dharmesh-Poddar provide preview link and screenshots of the enhancement that would better.

**Comment by Dharmesh-Poddar** [comment]
![screenshot from 2018-12-07 18-11-23](https://user-images.githubusercontent.com/32756751/49648486-03064080-fa4c-11e8-8c3a-a31eb986367e.png)
![screenshot from 2018-12-07 18-11-31](https://user-images.githubusercontent.com/32756751/49648488-039ed700-fa4c-11e8-90d5-67b15d63c627.png)

**Comment by Dharmesh-Poddar** [comment]
@siddharthgusain  please check my new pr #419 related to this issue
