### ISSUE TITLE
Autohide top menu bar similar to susi.ai

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#399]
The top menu bar on susi.ai has a nice autohide functionality. Please implement the same here.

![screenshot from 2018-11-27 11-00-53](https://user-images.githubusercontent.com/1583873/49075447-1be64900-f237-11e8-9955-b3a3bfa9120c.png)

**Comment by kksinghal** [comment]
I am almost done with it . Pls no one else start working on this.
