### ISSUE TITLE
Add scrollbars for dropdowns

### ISSUE THREAD

**Issue by supunTE** [fossasia/fossasia.org#409]
It's overflowing and not shows some links in the dropdown lists.
![image](https://user-images.githubusercontent.com/33794760/49326521-5b839c80-f579-11e8-948d-b5cf32890716.png)

![image](https://user-images.githubusercontent.com/33794760/49326533-8cfc6800-f579-11e8-9430-639bca12f42c.png)

### Add scrollbars like in https://github.com/fossasia/2019.fossasia.org/pull/35

# Am I working?
Yes of course!

**Comment by abishekvashok** [comment]
I guess instead of adding a scrollbar we could remove old events and competitions.

What do you say @mariobehling

**Comment by sarnava1** [comment]
Yes @abishekvashok that is a nice idea.
