### ISSUE TITLE
Fix the blog showcase section on fossasia.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#41]
The set up of http://blog.fossasia.org has changed as we moved the blog from Drupal to Wordpress. The result is that the showcase section "Blog" on the page does not work anymore. Please re-implement it on http://fossasia.org as follows:
- [x] Automatically show the last 10 blog entries of the FOSSASIA blog
- [x] Include heading, and below only show the first two paragraphs and a read more link
- [x] Use the xml file of http://blog.fossasia.org/feed/
- [ ] Also show images and links if they are in the blog post
- [x] Implement the posts as a slideshow

**Comment by VibhuKesar** [comment]
1st trouble : Uppermost fossasia image overlap with activities when changed the dimensions of web browser
![screenshot 15](https://cloud.githubusercontent.com/assets/20054569/16644926/ec9a59c4-443d-11e6-877d-6b4cd733efa6.png)

2nd trouble : Blog improvement 
[https://www.dropbox.com/s/l92fgaxa9gfvvz8/fossasia.org-gh-pages.zip?dl=0](url)

**Comment by VibhuKesar** [comment]
also should i make remote branch so that u can easily compare?
How to contribute so i found this the better way than dropbox,

**Comment by mariobehling** [comment]
Hi, thanks for your help. Each issue usually should only focus on one problem.

Please open another issue about the resolution problem.

For improvements, please use github and make a branch on your github account and show the changes.

After that please make a pull request. Thank you.

**Comment by VibhuKesar** [comment]
I have made a pull request .Thanks for giving me opportunity to contribute.

**Comment by vaibsharma** [comment]
for issue #41

@mariobehling ,hello sir , Sorry being absent for that long , from yesterday I started with this issue and for now I have been quite successful in getting .
1. Automatically show the last 10 blog entries of the FOSSASIA blog
2. Include heading, and below only show the first two paragraphs and a read more link
3. Use the xml file of http://blog.fossasia.org/feed/
Could you please guide me the type of styling that is required in the blog section for the display and also what images and which links you are referring in 4th implementation.

Thank you
best regards
Vaibhav Sharma

**Comment by mariobehling** [comment]
@vaibsharma Thank you for the updates. Please also document which technology you use in the Readme.md. I see feednami. Cheers.

**Comment by vaibsharma** [comment]
Yeah Sure sir

**Comment by vaibsharma** [comment]
@mariobehling  #48 added README.md for feednami

**Comment by vaibsharma** [comment]
#49 blog slider done! @mariobehling

**Comment by mariobehling** [comment]
Slider was not working and I had to revert it. Please implement a separate css and separate js files and do not change the existing ones. Thank you.

**Comment by vaibsharma** [comment]
Sorry for changing the existing files ,implemented a seperate css and js files #51 now it's working fine .
Thank you 
Best regards
Vaibhav

**Comment by mariobehling** [comment]
@vaibsharma Thank you, could you set up a test site on your repository, please? This would make it much easier. Cheers.

**Comment by vaibsharma** [comment]
vaibsharma.github.io/fossasia @mariobehling , I had deleted earlier CNAME file(sorry),as this made my server off for the entire day , .
