### ISSUE TITLE
Team members are repeated

### ISSUE THREAD

**Issue by Ridvmodi** [fossasia/fossasia.org#412]
![screenshot 286](https://user-images.githubusercontent.com/38110540/49330097-e1223f00-f5af-11e8-949a-4990ff4ec262.png)
![screenshot 287](https://user-images.githubusercontent.com/38110540/49330098-e7182000-f5af-11e8-9298-ba23297f485a.png)
They are repeated two times

**Comment by Dharmesh-Poddar** [comment]
can I work on it..

**Comment by Ridvmodi** [comment]
fixed already closing it @Dharmesh-Poddar
