### ISSUE TITLE
Add submenu for GCI and move annual pages to submenu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#422]
Please implement the submenu in the project tab. Ensure it also works on mobile views.

![screenshot from 2018-12-09 07-49-44](https://user-images.githubusercontent.com/1583873/49694254-38fc0f80-fb87-11e8-9f61-28e75a4d9734.png)

Example for submenu:

![screenshot from 2018-12-09 07-46-29](https://user-images.githubusercontent.com/1583873/49694255-41544a80-fb87-11e8-80f9-51c479acb554.png)

**Comment by kksinghal** [comment]
Working

**Comment by garvitkhandelwal** [comment]
Is this issue still open?

**Comment by kksinghal** [comment]
I have already done this , my PR is pending.

**Comment by mariobehling** [comment]
Good job so far. Please ensure this works on all pages. Thank you.

**Comment by kksinghal** [comment]
I will definitely work on this .
