### ISSUE TITLE
Split color of color-blocks for screensize 770-990px

### ISSUE THREAD

**Issue by kksinghal** [fossasia/fossasia.org#429]
Same color is applied here for screensize 770px to 990px .

<img width="771" alt="screenshot 2018-12-15 at 3 32 32 pm" src="https://user-images.githubusercontent.com/26023139/50041691-b8ee1200-007e-11e9-8c2f-6bb8fc78d2c6.png">

### Would you like to work on this issue ?
Yes

**Comment by KSNINJA** [comment]
Close via #430

**Comment by kksinghal** [comment]
Close via #430
