### ISSUE TITLE
The screenshts for the mobile apps is not responsive for mobile screens 

### ISSUE THREAD

**Issue by pranav1698** [fossasia/fossasia.org#442]
The screenshots for the mobile apps is not responsive to mobile screens

## Screenshots
![screenshot from 2018-12-18 22-42-53](https://user-images.githubusercontent.com/34754265/50170733-9bd37080-0316-11e9-970c-2e0d128a9951.png)
![screenshot from 2018-12-18 22-43-00](https://user-images.githubusercontent.com/34754265/50170742-9fff8e00-0316-11e9-83df-15f60a7055e4.png)
![screenshot from 2018-12-18 22-43-13](https://user-images.githubusercontent.com/34754265/50170757-a3931500-0316-11e9-94df-ff270a1eacfa.png)

**Comment by garvitkhandelwal** [comment]
It works fine on my device.
![screenshot 37](https://user-images.githubusercontent.com/24408454/50183583-8e2ee280-0338-11e9-8e01-60c9897af0d8.png)

**Comment by pranav1698** [comment]
![screenshot_20181218_211850](https://user-images.githubusercontent.com/34754265/50183704-e2d25d80-0338-11e9-8b72-f9e9ab827f97.jpg)
Strange, It is the same with my mobile
