### ISSUE TITLE
Weird looking negative space in "How can I support Fossasia" section when it is resized to the size of a tablet..

### ISSUE THREAD

**Issue by garvitkhandelwal** [fossasia/fossasia.org#445]
**In normal mode**
![screenshot 36](https://user-images.githubusercontent.com/24408454/50177920-350b8280-0329-11e9-8252-e3e669b0d1ed.png)

**In resized mode**
![screenshot 33](https://user-images.githubusercontent.com/24408454/50177966-4fddf700-0329-11e9-9a81-af7308de151c.png)
![screenshot 34](https://user-images.githubusercontent.com/24408454/50177973-54a2ab00-0329-11e9-8d07-d303f78be093.png)

**Comment by ShridharGoel** [comment]
Can be closed since it's fixed.
