### ISSUE TITLE
Email not responsive in "About Fossasia" section

### ISSUE THREAD

**Issue by garvitkhandelwal** [fossasia/fossasia.org#446]
![screenshot 35](https://user-images.githubusercontent.com/24408454/50178727-4e153300-032b-11e9-8990-41e539f20852.png)

**Comment by Dharmesh-Poddar** [comment]
@garvitkhandelwal  can I work on it

**Comment by garvitkhandelwal** [comment]
Yes sure!

**Comment by ravk1234** [comment]
can I work on it?

**Comment by garvitkhandelwal** [comment]
Sorry but I am working on it now.
