### ISSUE TITLE
Implement donation and supporter funding for fossasia.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#45]
Please implement donation and supporter funding for fossasia.org. Ensure it can continue to be hosted on github pages.
- [ ] Choose Donation or Regular Supporter
- [ ] If user chose donation offer: Choose amount
- [ ] If user chose regular supporter offer: Dropdown menu 5USD/month, 10USD/month, 50 USD/month, 100USD/month, 200USD/month, 1000USD/month
- [ ] Choose payment method (Paypal or Stripe)

**Comment by palnabarun** [comment]
I want to work on this issue but don't know where to start. Can anyone please help?

**Comment by rajakedia1** [comment]
I want to work on this issue. I have already work with payment methods.

**Comment by rajakedia1** [comment]
Can anyone tell me something about the layout, or about the designs so that I can start working on the page.

**Comment by Elgayar** [comment]
Is someone working on this issue?

**Comment by mariobehling** [comment]
This issue is free to take up. Solution should be a lightbox that pops up.

**Comment by Elgayar** [comment]
Is there a specific email that should receive the paypal payments?

**Comment by mariobehling** [comment]
yes: contact@fossasia.org

**Comment by abishekvashok** [comment]
@Elgayar updates would be awesome

**Comment by abhishek1995s** [comment]
Is this issue still open can I complete it

**Comment by abishekvashok** [comment]
It's still open @abhishek1995s pls do work on it.

**Comment by shubham-sr** [comment]
I want to contribute to this issue if its still open, how should I get started ?

**Comment by isuruAb** [comment]
@abhishek1995s  what is the status of this issue ? are you still working on this ?
