### ISSUE TITLE
Update About FOSSASIA Footer text

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#453]
Please update the footer text as follow:

FOSSASIA develops Open Source software and hardware solutions with a global developer community from its base in Asia and organizes [Open Technology events](https://events.fossasia.org) around the year. The mission of FOSSASIA is to improve people's lives by sharing open technologies, knowledge and resources and building a sustainable FOSS ecosystem. Projects include [conversational AIs](https://susi.ai), [science applications](https://pslab.io) and [event management tools](https://eventyay.com). The organization supports its most promising teams through a business incubator and runs coding programs and development contests like [Codeheat](https://codeheat.org/) to grow the developer community. FOSSASIA's annual [OpenTechSummit](https://fossasia.sg/) in Singapore is the premier Open Technology event in Asia for developers, tech companies, and contributors. FOSSASIA was founded in 2009 by [Mario Behling](https://twitter.com/mariobehling) and [Hong Phuc Dang](https://twitter.com/hpdang).

**Comment by Dharmesh-Poddar** [comment]
@mariobehling can I work on it..

**Comment by khan0604** [comment]
@mariobehling I have solved the issue. Please review my changes.
https://github.com/fossasia/fossasia.org/pull/456

**Comment by khan0604** [comment]
@mariobehling I have solved the issue. Please review my changes. https://github.com/fossasia/fossasia.org/pull/457
