### ISSUE TITLE
Create a sitemap.xml and html site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#46]
Please create a sitemap as
- [ ] sitemap.xml at http://fossasia.org/sitemap.xml
- [ ] an index.html sitemap at http://fossasia.org/sitemap/
- [ ] Include subdomains and the blog

**Comment by vaibsharma** [comment]
Will you please explain about this issue ?
Thank you !

**Comment by rajmeghpara** [comment]
@mariobehling , I have created both the files as u suggested,but i want u to check it before i create pull request,Here is the [link](https://drive.google.com/drive/folders/0B9EAusN0qvTXTHYteEpEdDJNZzA?usp=sharing).

**Comment by jigyasa-grover** [comment]
@rajmeghpara Feel free to submit a PR, we can then review and merge the changes. Cheers !

**Comment by gureks** [comment]
@mariobehling If this issue has not been resolved yet, please assign it to me.

**Comment by jigyasa-grover** [comment]
@rajmeghpara Updates on this pls ?

@gureks Go ahead with this in the meanwhile, submit a PR accordingly.

**Comment by mariobehling** [comment]
@gureks Thanks for joining! There is a basic sitemap here http://fossasia.org/sitemap.html and xml version here http://fossasia.org/sitemap.xml

Please help to add more details and improvements. Cheers.
