### ISSUE TITLE
Flickering in navbar menu

### ISSUE THREAD

**Issue by kksinghal** [fossasia/fossasia.org#460]
### Screenshot
![bug](https://user-images.githubusercontent.com/26023139/50403572-a1710080-07c5-11e9-808f-ca4913f84765.gif)
### Would you like to work on this issue ?
 No

**Comment by akshaycodrs** [comment]
Yes

**Comment by akshaycodrs** [comment]
But i have no idea give me direction to do it

**Comment by Jaggu-123** [comment]
@KSNINJA can I take this issue ??

**Comment by kksinghal** [comment]
@Jaggu-123 Yes, it is open to all .

**Comment by Jaggu-123** [comment]
Ok, I am working on it.

**Comment by Jaggu-123** [comment]
@KSNINJA can you please help me to reproduce this problem.

**Comment by kksinghal** [comment]
@Jaggu-123 Just hover over the elements quickly . 
By the way , it does not flicker when you are at the top of the page , I mean at scroll-position 0
