### ISSUE TITLE
Make "arrow" on dropdown for GCI submenu showing to the ">" right

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#461]
The GCI has the arrow in the wron g direction. Please fix it as below.

![screenshot from 2018-12-09 07-46-29](https://user-images.githubusercontent.com/1583873/49694255-41544a80-fb87-11e8-80f9-51c479acb554.png)

**Comment by Dharmesh-Poddar** [comment]
@mariobehling  would like to work on it..
