### ISSUE TITLE
Responsiveness issue:The menubar is not responsive 

### ISSUE THREAD

**Issue by akkshaychauhan** [fossasia/fossasia.org#462]
![isuue](https://user-images.githubusercontent.com/26792528/50425970-d2296680-08a7-11e9-89b1-14eff9ab3306.png)

**Comment by niravasher** [comment]
Hello, in this issue the contact link comes in the next line and it is not yet responsive, can I work on this issue @akkshaychauhan

**Comment by dewanshrawat15** [comment]
I would like to work on this @mariobehling
