### ISSUE TITLE
navbar's dropdown menus disappear when you try to point them 

### ISSUE THREAD

**Issue by Dharmesh-Poddar** [fossasia/fossasia.org#466]
navbar's dropdown menus disappear when you try to point them near color-block section.

        
![ezgif com-crop](https://user-images.githubusercontent.com/32756751/50450619-16267500-0955-11e9-90c1-ec18b744653f.gif)

**Comment by divyanshu132** [comment]
Can I work on this??

**Comment by Dharmesh-Poddar** [comment]
@divyanshu132  sure!! go on..

**Comment by yash-kedia** [comment]
can i work on this

**Comment by JaiParakh** [comment]
can i work on the issue?
