### ISSUE TITLE
Implement overlay on hover bottom of Android Apps images

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#469]
The Android apps images had an overlay with more information, but it was changing the space below and above the area as well.

Please implement a simple dark gray overlay on the bottom (a square covering the bottom of the image). Avoid Gradients.

Only add one effect that moves up from the bottom and include basic information about the app. Avoid having different effects for different lines. Keep it simple.

![screenshot from 2019-01-02 15-05-23](https://user-images.githubusercontent.com/1583873/50595256-d8b76f80-0e9f-11e9-9115-311a5961716b.png)

**Comment by Dharmesh-Poddar** [comment]
@mariobehling working..

**Comment by Dharmesh-Poddar** [comment]
@mariobehling  have you removed the span class consisting the basic information about the apps ?
