### ISSUE TITLE
Add link "Best Practices" on second line in About Menu Tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#472]
Please add this link on all pages https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

![screenshot from 2019-01-03 13-30-26](https://user-images.githubusercontent.com/1583873/50637835-d74b7d00-0f5b-11e9-8694-62d75aac898c.png)

**Comment by Dharmesh-Poddar** [comment]
@mariobehling working on it..
