### ISSUE TITLE
Include a back-to-top button on scrolling down

### ISSUE THREAD

**Issue by rbhatia46** [fossasia/fossasia.org#474]
On scrolling the website, a back-to-top button can be included in the bottom-right corner to make it easier to navigate back to the top. Only show the back to top button when the use moves the page. Ensure you use the existing scrolling implementation.

This issue is available for anyone. You can just start working on it without getting assigned.

**Comment by niravasher** [comment]
Hello sir, i want to fix this issue, can I work upon it? Along with this I will also change the styling of the scroll bar to make it look better

**Comment by Jaggu-123** [comment]
@rbhatia46 sir can I work on this issue ??

**Comment by ayanujju** [comment]
Can I work on it ?

**Comment by arghac14** [comment]
@rbhatia46  Assign me this.

**Comment by ji-kun** [comment]
I would like to take up this issue

**Comment by ayushmankumar7** [comment]
Assign this to me.

**Comment by supunTE** [comment]
Working on this.

**Comment by SARTHAK1SINGH** [comment]
@mariobehling IF this issue is open i would like to work on it.
As i downloaded the project and i can see it's not updated yet.

**Comment by Chaitanyassr** [comment]
> @mariobehling IF this issue is open i would like to work on it.
> As i downloaded the project and i can see it's not updated yet.

I have already submitted a working PR on this issue, you are not seeing it because it is not merged currently and waiting for the review... Thank you.

**Comment by mohitm15** [comment]
@Chaitanyassr there's already a `back to top` menu option at bottom.

![Screenshot 2020-01-19 02:17:11](https://user-images.githubusercontent.com/35539313/72670263-9d172580-3a61-11ea-9d7e-ab7041d82c41.png)

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr there's already a `back to top` menu option at bottom.
> 
> ![Screenshot 2020-01-19 02:17:11](https://user-images.githubusercontent.com/35539313/72670263-9d172580-3a61-11ea-9d7e-ab7041d82c41.png)

yes, but the page doesnt have back to the top on the right side when scrolling down.

**Comment by mohitm15** [comment]
@Chaitanyassr I don't think this is necessary?
