### ISSUE TITLE
Error 404. There is no way to add or propose at least new ideas (or ready to use repositories) to the fossasia organization. 

### ISSUE THREAD

**Issue by Yahhi** [fossasia/fossasia.org#475]
The only link I found to apply with a new idea is https://fossasia.org/apply.html it gives error 404.
I want to suggest creating a new project for pslab hardware. It will connect with pslab through Bluetooth connection and will be written in Flutter, so iOS users can have all the opportunities the hardware can give them. 
On site there should be some form to add ideas and discuss them. Gitter chats are almost useless because the main part here is introduction and greetings of new members and congratulations to winners, no actual discussion.

**Comment by mariobehling** [comment]
This is a great idea. Would be awesome if you get started!

If you would like to start a new subproject the usual way is as follows: 
1. At first engage in the community and mention your idea on the specific Gitter channel of the project itself.
2. Create a Github repository in your personal area and start adding information on the Readme file and most importantly start coding.
3. Formulate an email to the project mailing list and post the information also to the Gitter channel. Include any links you might have as references and the link to your Github repo.
4. Update the community on the channels about your projects and encourage the community to review your PRs and join your project.
5. Once the project has some code showing more of the potential of your project you can propose to move it to FOSSASIA as an organization.

The correct page for program applications by the way is here: https://fossasia.org/apply/

I should add the above to our best practices. So, assigning this issue to me.

**Comment by Tharindupriyaharshana** [comment]
do you fixed this issue?

**Comment by mariobehling** [comment]
Correct link for application is https://fossasia.org/apply/index.html
