### ISSUE TITLE
Images not showing on subpages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#476]
Background images and some other images are not showing up anymore on subpages, e.g. https://fossasia.org/about/

Please identify the reason and fix it.

![screenshot from 2019-01-11 13-38-45](https://user-images.githubusercontent.com/1583873/51034311-ac3dda80-15a6-11e9-8ef3-263812a645b1.png)

**Comment by Dharmesh-Poddar** [comment]
@mariobehling working on it..

**Comment by kksinghal** [comment]
@Dharmesh-Poddar Sorry , I forgot to mention here . My PR is ready .

**Comment by Dharmesh-Poddar** [comment]
@KSNINJA  No problem bro :)

**Comment by muarachmann** [comment]
Can this issue be closed since it is resolved @KSNINJA
