### ISSUE TITLE
Add "Project Ideas" to menu below "Contribute on Github"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#481]
Please add the link "Project Ideas" to https://labs.fossasia.org/ideas.html below "Contribute on Github"

![screenshot from 2019-01-30 21-24-36](https://user-images.githubusercontent.com/1583873/52010587-30182200-24d6-11e9-9240-e9b1d5c0e0f1.png)

**Comment by Jaggu-123** [comment]
@mariobehling I will do this task.

**Comment by Jaggu-123** [comment]
@mariobehling I am not getting the file for url starting with someting "labs.fossasia.org" or "events.fossasia.org". So suggest me whether to do changes in these files or not.

**Comment by ICEBERG98** [comment]
If the Issue Has been fixed Please Mark this as fixed,
If not is it open to Assignees?
