### ISSUE TITLE
Removal of Google plus social icons

### ISSUE THREAD

**Issue by satya-vinay** [fossasia/fossasia.org#489]
As Announced by [Google](https://timesofindia.indiatimes.com/gadgets-news/google-consumer-accounts-to-be-discontinued-on-april-2-heres-all-you-need-to-know/articleshow/67768585.cms), the Google plus is going shutdown on April 2, 2019 and all accounts and pages will deleted.

**To-Do:**
So before that its better to remove the Google plus social icons from the website.

**Would you like to work on the issue?**
Yes

**Comment by hjain5164** [comment]
I have removed the icons from the website
