### ISSUE TITLE
Implement new top menu on all pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#493]
The index.html page has an updated menu. Please implement it on all pages. 
* Please ensure you keep internal links working.
* Also show a menu option on mobile pages

**Comment by kushthedude** [comment]
@mariobehling Is it up for grabs?

**Comment by mariobehling** [comment]
Yes, please also ensure a drop down menu shows up on mobile pages.

**Comment by kushthedude** [comment]
Workin on it , will include a dropdown nav
