### ISSUE TITLE
Implement Web Tweets with loklak API instead of twitter API on FOSSASIA sites

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#5]
**Objective**

There is already a working implementation of loklak webtweets at https://github.com/fossasia/fossasia-loklak-webtweets. Please implement loklak tweets to substitute the current implementation using the twitter API on http://2015.fossasia.org, http://2016.fossasia.org and http://fossasia.org. Keep the design as is and ensure tweets are looping.

**Requirements**
- use http://loklak.org to implement the feature
- documentation at http://loklak.org/api.html

**Expected Outcome**
- webtweets on FOSSASIA sites using loklak
- design stays as is
- tweets are looping in a slider (as is)
- document changes and how to adapt functioning in Readme.md

**Other**

Keep the existing design

![screenshot from 2016-01-15 15 02 40](https://cloud.githubusercontent.com/assets/1583873/12354885/4d80988a-bb99-11e5-9d6d-9e73a7207580.png)
http://fossasia.org

![screenshot from 2016-01-15 15 03 14](https://cloud.githubusercontent.com/assets/1583873/12354880/42114968-bb99-11e5-8bc0-9060623f218c.png)
http://2016.fossasia.org

**Comment by codethejason** [comment]
@mariobehling I have implemented Loklak into each of the sites and referenced the loklak-webtweets README for documentation in the HTML.

**Comment by mariobehling** [comment]
@codethejason Could you check please to correct the design slightly. Only links are bold und underlined, regular text is not bold.

Is it also possible to implement "Posted xyz minutes/hours/days ago"?

**Comment by codethejason** [comment]
@mariobehling Links now display as bold and regular text is not bold. Also, all tweets are from the @fossasia account. I decided to implement tweeted x hours ago because it makes it more readable in my opinion.

**Comment by mariobehling** [comment]
Good job! Thanks.
