### ISSUE TITLE
advanced developer page giving 404 error

### ISSUE THREAD

**Issue by Divya-5** [fossasia/fossasia.org#508]

**Comment by Divya-5** [comment]
![screencapture-events-fossasia-org-adp-2019-05-26-18_11_33](https://user-images.githubusercontent.com/43536638/58381966-b73b5980-7fe1-11e9-9c65-a06673f3670d.png)

**Comment by mariobehling** [comment]
Correct link is https://fossasia.org/adp

Works for me. Please identify pages where that contain the wrong link, if any.
