### ISSUE TITLE
Navbar text remains barely visible on going to previous-visited page, until the page is scrolled.

### ISSUE THREAD

**Issue by ShivanshRakesh** [fossasia/fossasia.org#513]
On going to previous visited page (go Back or go Forward button in browser), the text on navigation bar does not appear correctly (barely visible). Also, the background remains transparent. 

On navigating to previous page: (Notice slightly visible FOSSASIA logo)
![Screenshot from 2019-06-06 21-09-49](https://user-images.githubusercontent.com/49039969/59046710-1893e000-88a0-11e9-908e-8dbd54a1e2d3.png)

On scrolling:
![Screenshot from 2019-06-06 21-09-55](https://user-images.githubusercontent.com/49039969/59046739-23e70b80-88a0-11e9-90cd-23a5ef5a05a8.png)

**Comment by akshatra** [comment]
Seems to be working fine when I copied this on my local machine.
Let's see what can be done.
