### ISSUE TITLE
Improve mobile screen section / add buttons for Playstore/Fdroid / Add apps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#519]
Please improve the app section as follows:
* [ ] add a semitransparent background and text with the app name on the bottom of the app screenshots
* [ ] add buttons for a) Playstore, b) Fdroid, c) GitHub below each app screen
* [ ] add other apps
  * [ ] Badge Magic
  * [ ] Eventyay Attendee App
  * [ ] Eventyay Organizer App

**Comment by ShivanshRakesh** [comment]
Is the issue still open? If yes, I would like to work on it.
