### ISSUE TITLE
Improve Mobile App Section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#526]
Provide more relevant screens showing more of the main feature of the apps in the bottom row. Image size should be Width: 364 x Height: 647

![Screenshot from 2019-08-10 05-26-17](https://user-images.githubusercontent.com/1583873/62816975-6e4e6800-bb2f-11e9-8360-3366f17edb3b.png)

**Comment by NamanZelawat** [comment]
I would like to work on it.

**Comment by NamanZelawat** [comment]
And I would also like to add some effects like <a href = "http://css3.bradshawenterprises.com/flip/">flipping</a> or <a href="http://css3.bradshawenterprises.com/cfimg/">fading(demo3)</a> so that we can display more than one image in the space of one image.

**Comment by NamanZelawat** [comment]
@mariobehling  All changes(flipping effect) are made you can check them <a href = "https://namanzelawat.github.io/fossasia.org/">here</a>. If there are some more changes required please comment.
