### ISSUE TITLE
Add info area with expanding image title overlay effect on top of Android app screenshots

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#527]
Please implement a simple dark gray overlay on the bottom (a square covering the bottom of the image). Avoid Gradients. Compare the general effect here: https://www.w3schools.com/howto/howto_css_image_overlay_title.asp

Only add one effect that moves up from the bottom and include 
* Name of app
* One Scroll-over show: Short description of the app. **Please make the effect in the way that the bottom gray bar expands from bottom to 2/3 of the app image - like make it moving in from the bottom with the description, please.**

Below the app screenshot please add a badge for a) Playstore and b) Fdroid.

![screenshot from 2019-01-02 15-05-23](https://user-images.githubusercontent.com/1583873/50595256-d8b76f80-0e9f-11e9-9115-311a5961716b.png)

This issue is free to take up for anyone.

**Comment by amreshk005** [comment]
Can I take this issue?

**Comment by arghac14** [comment]
@mariobehling Can I work on this?

**Comment by Aaryan-kapur** [comment]
can i start working on this, I would love this

**Comment by ayushiitr2901** [comment]
Is this issue still open, I will like to work on this

**Comment by Aaryan-kapur** [comment]
Is this issue still open, I will like to work on this

**Comment by mariobehling** [comment]
No need to claim it. Just go ahead and solve it.

**Comment by Aaryan-kapur** [comment]
oh okay thank you!!
