### ISSUE TITLE
Fix height of gray events dropdown menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#53]
The events dropdown menu currently does not show all links. Please ensure the box is automatically expanded to show all links of the menu on all FOSSASIA pages and subdomains.

![screenshot from 2016-09-14 17 38 49](https://cloud.githubusercontent.com/assets/1583873/18518966/61a8f05a-7aa2-11e6-829c-3b5e0e4e02cf.png)

**Comment by sandmanx** [comment]
@mariobehling  Fixed the issue by forcibly fixing the height of dropdown menu at 400px using inline styling. PR #56

**Comment by bettersandeep** [comment]
@mariobehling The only solution that I could find was to forcibly set the height of the dropdown menu to 400px using inline css. So should I go ahead and create multiple pull requests for all the pages?

**Comment by bettersandeep** [comment]
@mariobehling You can see how it works in PR #56. This is for the home page only. I will do the same for all pages in all fossaia websites that are currently live.

**Comment by mariobehling** [comment]
@sandmanx Thanks. Looks good. Please increase height even more. The link to the code of conduct is still missing. cheers.

**Comment by bettersandeep** [comment]
@mariobehling Issue fixed for the main website on two pages, index.html and about.html by PR #58 and #57 respectively. You can close the issue now.

**Comment by Shivang-Bhandari** [comment]
Rather than giving a fixed height i think a overflow for the section would be a more appropriate solution to the problem.
