### ISSUE TITLE
Implement Top Menu Bar from Index.html on all other pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#530]
The top menu bar has changed and links have been change. Please update all other page in this repo following the index.html. Please ensure you keep relative links e.g. use ./about/ instead of linktin to https://fossasia.org/about/.

**Comment by asha15** [comment]
@mariobehling  Shall i work on this ?

**Comment by mariobehling** [comment]
Go ahead, please.

**Comment by mariobehling** [comment]
Please make the top menu on all fossasia pages and subpages like labs.fossasia.org same as in fossasia.org main page. Thanks.

**Comment by aditya20t** [comment]
If this issue is open can I take a look?

**Comment by liveHarshit** [comment]
> If this issue is open can I take a look?

It is open. Please go ahead.
