### ISSUE TITLE
Page fossasia.org/coc/index.html broken due to wrong CSS links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#531]
THe page fossasia.org/coc/index.html is broken as links and images are linked in another directory. Please help to fix it.

**Comment by Yachitha** [comment]
can I take this? I'll check this out and give a feedback.

**Comment by liveHarshit** [comment]
> can I take this? I'll check this out and give a feedback.

Go ahead.

**Comment by Yachitha** [comment]
**js/twitterfetcher.min.js** this file is not found in the **js** directory? has anyone changed the file location?

**Comment by Yachitha** [comment]
@mariobehling are their any mistakes in the code. please let me know I'll try my best to resolve them.

**Comment by keysangyonthan** [comment]
Is this issue still open, if it is I would like to work on it!

**Comment by liveHarshit** [comment]
> Is this issue still open, if it is I would like to work on it!

Please go ahead

**Comment by aditya20t** [comment]
I fixed this issue. PR #550

**Comment by aditya20t** [comment]
Also #552 is the enhancement solution.

**Comment by liveHarshit** [comment]
@adad20 Always mention fixes in the PR description so that the issue will automatically get closed when the PR got merged.
