### ISSUE TITLE
Add a GitHub icon to footer and sidebar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#54]
Currently the Github icon is missing on the footer and sidebar.

Please add it
- [x] to the sidebar

![screenshot from 2016-09-15 10 53 59](https://cloud.githubusercontent.com/assets/1583873/18544373/8f1e5e3e-7b34-11e6-8b16-44bdaa6664c3.png)
- [x] to the footer

![screenshot from 2016-09-15 10 53 42](https://cloud.githubusercontent.com/assets/1583873/18544390/a04a4ccc-7b34-11e6-863d-33e859bd54a9.png)

**Comment by jigyasa-grover** [comment]
Closing. Fixed via PR https://github.com/fossasia/fossasia.org/pull/59.
