### ISSUE TITLE
"MORE EVENTS"  in Events (nav-bar) needs some change

### ISSUE THREAD

**Issue by ayushmankumar7** [fossasia/fossasia.org#547]
![Screenshot from 2019-10-22 10-35-06](https://user-images.githubusercontent.com/41910134/67260195-a40cb700-f4b7-11e9-8652-0e3a8048b674.png)

**Comment by ayushmankumar7** [comment]
This can be made better.

**Comment by preyunk** [comment]
Can you please tell what needs to be changed?

**Comment by SauravP97** [comment]
I have proposed a PR #549  for this issue, Kindly have a look

**Comment by ayushmankumar7** [comment]
I have already made a pull request.  Let's see what the owners decide.
