### ISSUE TITLE
Implement a better back to top

### ISSUE THREAD

**Issue by kushthedude** [fossasia/fossasia.org#548]
Current back to the top is too ugly, The transition should be should scrolling rather than going directly upwards.
Improve the following

**Comment by arron-tij** [comment]
Please share the link of the pages where this issue exists, because all the back to top links that I saw already had scroll transition

**Comment by kushthedude** [comment]
> Please share the link of the pages where this issue exists, because all the back to top links that I saw already had scroll transition

See the `fossasia.org` index page

**Comment by abhishekvirat0** [comment]
Hi, My name's Abhishek and I would like to work on this issue

**Comment by kushthedude** [comment]
Sure, Go ahead.

**Comment by abhishekvirat0** [comment]
Thanks !
what type of back to the top you want ?

**Comment by kushthedude** [comment]
Current button looks good, just make sure the transition is smooth scroll

**Comment by yash-kedia** [comment]
the button also should have a border radius of 10px

**Comment by abhishekvirat0** [comment]
ok, I'll update once done.

**Comment by ayushiitr2901** [comment]
Is this issue still open, I would love to work on this
