### ISSUE TITLE
Revert Lazy loading on index.html as it results in issues

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#555]
Lazy loading on start page results in the issue that linking into sections on the page is not working smoothly. Please revert lazy loading on the index.html page.

**Comment by mariobehling** [comment]
Changes were done in this PR: https://github.com/fossasia/fossasia.org/pull/434

Please help to revert these changes.

**Comment by srishtiBajpai** [comment]
Hey! I would like to work on this issue and had a brief look over index.html file and found that the changes as done in issue #434 have been reverted back and lazy loading features are no more implemented (or may be i have missed it). Please help me to forward resolve this issue

**Comment by srishtiBajpai** [comment]
Hey! I would like to work on this issue and had a brief look over index.html file and found that the changes as done in issue #434 have been reverted back and lazy loading features are no more implemented (or may be i have missed it). Please help me to further resolve this issue

**Comment by kushthedude** [comment]
> Hey! I would like to work on this issue and had a brief look over index.html file and found that the changes as done in issue #434 have been reverted back and lazy loading features are no more implemented (or may be i have missed it). Please help me to further resolve this issue

@srishtiBajpai The changes are not reverted I suppose, Since the PR is not linked to any reverting PR

**Comment by kushthedude** [comment]
> Hey! I would like to work on this issue and had a brief look over index.html file and found that the changes as done in issue #434 have been reverted back and lazy loading features are no more implemented (or may be i have missed it). Please help me to further resolve this issue

You may take it if you want to work on it. Thanks
