### ISSUE TITLE
Align all social icons in one line for mobile 

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/fossasia.org#558]
![Screenshot from 2019-11-24 16-23-52](https://user-images.githubusercontent.com/56407566/69493634-ebcb9780-0ed6-11ea-9486-dc844dc8edf7.png)
**Additional context**
i am working on it .

**Comment by Aaryan-kapur** [comment]
can i start to work on this?

**Comment by maze-runnar** [comment]
Already a pr is open .

**Comment by Aaryan-kapur** [comment]
oh okay thankyou so much!
can you suggest me any similar projects i could contribute to?

**Comment by maze-runnar** [comment]
Open-event and susi
