### ISSUE TITLE
FOSSASIA

### ISSUE THREAD

**Issue by Ojaswy** [fossasia/fossasia.org#575]
How do I join this Organisation?

**Comment by liveHarshit** [comment]
Is it an issue?

**Comment by Ojaswy** [comment]
No, but it would be nice to include the steps to join on the Website. Hence opened one here.

**Comment by liveHarshit** [comment]
> No, but it would be nice to include the steps to join on the Website. Hence opened one here.

Orgmanager build is failing currently. The link is here: http://orgmanager.miguelpiedrafita.com/o/fossasia
For now, only admin can invite individually.
