### ISSUE TITLE
Missing social icons

### ISSUE THREAD

**Issue by pranavkarthik10** [fossasia/fossasia.org#576]
There is no icon for the Docker, Gitlab, or Crunchbase profiles for FOSSASIA in the footer.

**Comment by ShivanshRakesh** [comment]
@mariobehling I would like to work to work on this issue.

**Comment by Ojaswy** [comment]
@pranavkarthik10 Can you post the link of the webpage where this issue persists?

**Comment by harsh-kukreja** [comment]
@mariobehling can you provide the links for docker gitlab and crunchbase profiles for the FOSSASIA so tha i can add and work on this issue

**Comment by harsh-kukreja** [comment]
@pranavkarthik10  or @mariobehling can you provide the links for docker gitlab and crunchbase profiles for the FOSSASIA so tha i can add and work on this issue

**Comment by mohitm15** [comment]
@hpdang Please close the issue if PR got merged.
