### ISSUE TITLE
Website: Update new FOSSASIA Address

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#583]
The new FOSSASIA Address in Singapore is:

12 Eu Tong Sen Street #08-169 Singapore 059819

Please update it and add the correct link to OpenStreetMap on all pages.

**Comment by kumuditha-udayanga** [comment]
I'm working on it.

**Comment by kumuditha-udayanga** [comment]
@mariobehling the changes have been done please review #585 😇

**Comment by kushthedude** [comment]
@mariobehling Close.
