### ISSUE TITLE
Github logo disappear in the profile links

### ISSUE THREAD

**Issue by kumuditha-udayanga** [fossasia/fossasia.org#600]
# Description 
The GitHub logo is has been disappeared in the profile links

# Are you working on this issue
[x] Yes
[ ] No

# Screenshot
<img width="1656" alt="Screenshot 2019-12-22 at 16 08 24" src="https://user-images.githubusercontent.com/27630091/71320710-4f94b080-24d5-11ea-8bf9-5cb93e7f9700.png">

**Comment by mariobehling** [comment]
This is a new issue. Which PR caused this issue? Please identify and help to revert the change that caused it.

**Comment by kumuditha-udayanga** [comment]
@mariobehling I think this is the PR (https://github.com/fossasia/fossasia.org/pull/593)

**Comment by mariobehling** [comment]
Thanks. Could you make a PR reverting this PR and provide a test page, please?

**Comment by kumuditha-udayanga** [comment]
okay sure

**Comment by kumuditha-udayanga** [comment]
@mariobehling reverted successfully #603

**Comment by pranavkarthik10** [comment]
@mariobehling Instead of reverting the PR, I fixed the issue by updating all of the icons #609.
