### ISSUE TITLE
missing social icons

### ISSUE THREAD

**Issue by rajatvarma** [fossasia/fossasia.org#616]

**Comment by Rishi007-web** [comment]
I want to work on this issue.

**Comment by keysangyonthan** [comment]
where?

**Comment by mohitm15** [comment]
@rajatvarma specify the issue with more clarification so that @keysangyonthan can work on it. Otherwise close this.

**Comment by Kushagraw12** [comment]
Please provide some description, so that i can take this up. I want to contribute.

**Comment by amulyavw** [comment]
I want to work on this issue. Please provide a proper description
