### ISSUE TITLE
Join FOSSASIA.. How do I join this Organisation?

### ISSUE THREAD

**Issue by sayanmondal2098** [fossasia/fossasia.org#617]
How i can join there ?

**Comment by Dishebh** [comment]
@sayanmondal2098 You can join the organization by interacting with the community, solving and / or finding out bugs, guiding others along the way, etc.
For more queries, you can head to the gitter channel: 
https://gitter.im/fossasia/home

**Comment by mohitm15** [comment]
@sayanmondal2098  Have this conversation on gitter and don't create such vague issues.Close this
