### ISSUE TITLE
Reduce the images size for better performance

### ISSUE THREAD

**Issue by Dishebh** [fossasia/fossasia.org#619]
There are many images in the img directory that exceeds the size of 400kb or 500 kb. Shrink them to less than 100kb (except for the images covering more than 70% of screen width) for optmization and better performance of the website.

**Comment by Rishi007-web** [comment]
I want to work on this issue.

**Comment by SARTHAK1SINGH** [comment]
@Dishebh i would like to work on this issue. 
can i work on it.

**Comment by Dishebh** [comment]
Sure, go ahead

**Comment by SARTHAK1SINGH** [comment]
[Reduced the images size for better performance #661](https://github.com/fossasia/fossasia.org/pull/661)

@mariobehling @Dishebh please review it.
