### ISSUE TITLE
Membership(text)is overlaping the text need to be fixed.

### ISSUE THREAD

**Issue by Chaitanyassr** [fossasia/fossasia.org#627]
![Screenshot (127)](https://user-images.githubusercontent.com/30374226/71729445-c29f0f00-2e65-11ea-8be7-710e82776711.png)

**Comment by SARTHAK1SINGH** [comment]
if this issue is open i would like to work on it.

**Comment by Chaitanyassr** [comment]
> if this issue is open i would like to work on it.

This issue has been solved... Thank you.
