### ISSUE TITLE
Fix broken GitHub image 

### ISSUE THREAD

**Issue by dipu989** [fossasia/fossasia.org#629]
Steps to reproduce - 
Hover over the team members profile here  at https://fossasia.org/team/
Github image is not properly displayed.

Would you like to work on this?
No, Open for beginners!

**Comment by DevanshCodes** [comment]
Can I work on this?

**Comment by mariobehling** [comment]
In order to fix this, please revert PR https://github.com/fossasia/fossasia.org/pull/621

It can not be reverted automatically. So, it would be great, if you could help to simply revert it manually.

**Comment by abishekvashok** [comment]
@mariobehling that would take a force push, it might break the forks, can I make a PR?

**Comment by mariobehling** [comment]
Already done. Thanks. Closing it.
