### ISSUE TITLE
Section-header section getting cut mid-way

### ISSUE THREAD

**Issue by Dishebh** [fossasia/fossasia.org#637]
### Description
`section-header` gets cut almost through midway on the web page

### Screenshot of the issue:
![Screenshot from 2020-01-08 23-48-33](https://user-images.githubusercontent.com/43489708/72004542-a2aa8980-3271-11ea-9991-edd5ccbabbfe.png)

**Comment by SARTHAK1SINGH** [comment]
@Dishebh is this issue still open . i would like to work on it.

**Comment by Dishebh** [comment]
I have already submitted a PR, pls look for some other issue. Thanks
