### ISSUE TITLE
Add yaydoc.org into dropdown menu on all FOSSASIA.org Github pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#639]
Yaydoc is running on yaydoc.org. Please add the link to the FOSSASIA dropdown menu into the "projects" tab above "Meilix".

![Screenshot from 2020-01-09 16-51-59](https://user-images.githubusercontent.com/1583873/72063755-68d49400-3300-11ea-8709-b9e73aa7321a.png)

**Comment by mohitm15** [comment]
@mariobehling is this still an issue because I can see the yaydoc in the dropdown at official website.at (https://fossasia.org/). Kindly close this.
