### ISSUE TITLE
Navbar Crash for Ipad Portrait Orientation 

### ISSUE THREAD

**Issue by Shivang-Bhandari** [fossasia/fossasia.org#64]
The Navbar's Hamburger Button does not appear fully for ipad portrait mode ( 768 px \* 1024 px ) @mariobehling @the-dagger

**Comment by Shivang-Bhandari** [comment]
![2](https://cloud.githubusercontent.com/assets/16368588/18974046/69b9dbec-86be-11e6-9799-6aa2ffb5cefd.png)

**Comment by jigyasa-grover** [comment]
@Shivang-Bhandari Help us resolve the issue pls.

**Comment by Shivang-Bhandari** [comment]
yeah sure ill get to it and check where things are going off track, i hope by the end of the weekend ill be able to resolve the issue @jig08 .

**Comment by Shivang-Bhandari** [comment]
@jig08 i have fixed the issue.

**Comment by jig08** [comment]
@Shivang-Bhandari Your PR referenced this issue ? Attach a link of the same.

**Comment by Shivang-Bhandari** [comment]
@mariobehling The issue is that there is an additional white space in the whole page due to which the hamburger icon is not displayed fully and the user has to scoll a bit horizontally as visible in the screenshot previously attached. After looking into the home page i found that this was being caused due to the footer elements going out of place. I am attaching screenshots of the navbar display as well as the footer as they are on fossasia.org kindly take a look at them.
![navbar](https://cloud.githubusercontent.com/assets/16368588/19047229/89b36596-89be-11e6-9972-81b83b24ebf7.png)
![footer](https://cloud.githubusercontent.com/assets/16368588/19047228/8992f950-89be-11e6-90ec-6c3efc620e0e.png)

**Comment by Shivang-Bhandari** [comment]
@mariobehling the issue can only be resolved by changing the width of the elements in the footer as the email address's unusual width is causing the issue in the first place.

**Comment by mariobehling** [comment]
@Shivang-Bhandari Thanks for pointing this out. Please try to play around with css, e.g. a result could be that in smaller resolutions the page shows "fossasia@google...." instead of the full email.

**Comment by Shivang-Bhandari** [comment]
@mariobehling rather than hiding the whole email address wouldn't it be better to fit it in the page itself by adjusting the classes for smaller resolutions like i did in my commit which was reverted ?

**Comment by mariobehling** [comment]
Your adjustments changed the width distribution of the footer columns. This is not a desired outcome as the footer should be distributed evenly. Cheers.

**Comment by Shivang-Bhandari** [comment]
@mariobehling Ok sir so should i make changes to hide the whole email address for the smaller screen resolutions ?

**Comment by mariobehling** [comment]
We can also think about another solution, but it sounds like the easiest to go with for now.

**Comment by Shivang-Bhandari** [comment]
@mariobehling Sorry for the late reply but i am thinkig that it would be a better idea to put Just 'FOSSASIA' instead of the whole link and then add a mailto link to it which would be much more convinient for the users too.

**Comment by Shivang-Bhandari** [comment]
if you feel the idea would be ok then i'll get it done asap

**Comment by mariobehling** [comment]
@Shivang-Bhandari This field is an email field. So, Email address there is the preferred solution. As this is quite a long discussion about a small issue, I am opening this issue to others and unassigning this. If you still think you can solve it, simply make a pull request. Cheers.
