### ISSUE TITLE
Add Hub Docker icon to the website

### ISSUE THREAD

**Issue by hoangdatngo** [fossasia/fossasia.org#641]
I want to add Hub Docker icon to the fossasia website

**Comment by ayushmankumar7** [comment]
Where exactly, on the page, do you want it ?

**Comment by abishekvashok** [comment]
> Hub Docker 

is fossasia there on Hub Docker?

**Comment by SARTHAK1SINGH** [comment]
@hoangdatngo where do you want this icon, i would love to work on this issue.

**Comment by SARTHAK1SINGH** [comment]
@mariobehling can i work on this issue?
