### ISSUE TITLE
There's a redundancy in the teams page

### ISSUE THREAD

**Issue by Dishebh** [fossasia/fossasia.org#643]
### Description:
`Abhinav Raj` profile repeats in the http://fossasia.org/team page.

### Screenshot for the issue:
![Screenshot from 2020-01-11 10-30-12](https://user-images.githubusercontent.com/43489708/72199109-6471bd80-345d-11ea-9c05-488a780a02ef.png)
![Screenshot from 2020-01-11 10-30-16](https://user-images.githubusercontent.com/43489708/72199112-69367180-345d-11ea-9377-1b6d2817db52.png)

**Comment by SARTHAK1SINGH** [comment]
@Dishebh is this issue open. Because i would like to work on it.

**Comment by Dishebh** [comment]
I have already submitted a PR, pls look for some other issue. Thanks

**Comment by mohitm15** [comment]
@Dishebh Also make change for `Praveen Ojha`

**Comment by Dishebh** [comment]
@mohitm15 Done. Thanks for mentioning.
