### ISSUE TITLE
Navbar Crash at 769 X 392 px

### ISSUE THREAD

**Issue by Shivang-Bhandari** [fossasia/fossasia.org#65]
The Fossasia logo merges with the navbar menu.
![3](https://cloud.githubusercontent.com/assets/16368588/18974183/304bdf58-86bf-11e6-9f0d-8e3bd83f5f1c.png)

**Comment by Shivang-Bhandari** [comment]
Extra White Space too generates in the extreme right which decreases with increase in width

**Comment by jigyasa-grover** [comment]
@Shivang-Bhandari Yes, the issue is there. Would you like to take this up ?

**Comment by Shivang-Bhandari** [comment]
Ill give it a look on my end, i hope i can find a fix. @jig08
