### ISSUE TITLE
Overlapping of Copyright text on sidebar

### ISSUE THREAD

**Issue by singhksandeep25** [fossasia/fossasia.org#66]
On decreasing the length of the browser and opening the sidebar, the Copyright text overlaps with the options available in the sidebar.
![page-shot-2016-10-2-fossasia 2](https://cloud.githubusercontent.com/assets/14184381/19017084/15e209ce-884c-11e6-829d-cad345161a1e.png)

**Comment by bettersandeep** [comment]
Also, a typo exists in the third option (Event Management)

**Comment by bettersandeep** [comment]
One way to fix this is to fix the copyright text at the bottom of the page. But that approach causes it to disappear on decreasing the height of the browser. Should I go ahead with this approach?

**Comment by daminisatya** [comment]
@sandmanx these are purely user experience problems, please create a pull request, we will test it. And then we can decide on the right fix or merge the existing one!

**Comment by bettersandeep** [comment]
Fixed wrt PR #67
