### ISSUE TITLE
In side Navbar "Copyright 2009-2019 Creative Commons By License, FOSSASIA FOSSASIA" isn't visible

### ISSUE THREAD

**Issue by Yashank18** [fossasia/fossasia.org#669]
Inside the side navbar, the bottom line isn't visible fully.
Will like to work on it.
![Screenshot (92)](https://user-images.githubusercontent.com/46098062/74166459-9a68b400-4c4c-11ea-88fd-642f2b1470db.png)

**Comment by snitin315** [comment]
@Yashank18 are you still on it or can i give it a try?

**Comment by Yashank18** [comment]
> @Yashank18 are you still on it or can i give it a try?

I am working on it,I was waiting for someone to assign me this task.

**Comment by snitin315** [comment]
> > @Yashank18 are you still on it or can i give it a try?
> 
> I am working on it,I was waiting for someone to assign me this task.

Nope No one is going to assign you , you created the issue and you commented I will work on this , the task is automatically assigned to you just create a Pull request.

**Comment by Yashank18** [comment]
Okay, thank you. I will create the pull request as soon as possible.

**Comment by Yashank18** [comment]
#680

**Comment by Yashank18** [comment]
@snitin315 
Created Pull Request
#680

**Comment by snitin315** [comment]
Don't add comment like this to link pull request with issues. Github already provides good feature for that , add corresponding  issue in PR description , also everyone who have subscribed receives an email notification , for every pull request anyone creates , every comment any one adds , Hence these unnecessary activities should be avoided . Our emails are already flooded with github notifications.
