### ISSUE TITLE
Text overlaps with header in License Agreements section of the page

### ISSUE THREAD

**Issue by bharat-1809** [fossasia/fossasia.org#673]
Here's a screenshot of the issue: 

![Screenshot from 2020-02-11 21-26-12](https://user-images.githubusercontent.com/58745044/74254349-5510b900-4d16-11ea-8064-dd50e0cbd138.png)

I would like to work on this problem. Kindly assign me this issue.

Thanks

**Comment by Mayank0022** [comment]
is this issue is open, i would like to work on it
