### ISSUE TITLE
Lists are not properly indexed

### ISSUE THREAD

**Issue by prateekrai123** [fossasia/fossasia.org#683]
![issue](https://user-images.githubusercontent.com/54741353/76148025-5391a100-60c8-11ea-96df-a63844517f49.png)
These two lists are not proper according to the UI

**Comment by abishekvashok** [comment]
Do you want to work on it? If yes, please go on

**Comment by prateekrai123** [comment]
Yes I want to work on it.
Thanks and regards.

**Comment by prateekrai123** [comment]
Yes I want to work on it.
Thanks.

**Comment by prateekrai123** [comment]
![solved issue](https://user-images.githubusercontent.com/54741353/76160847-a82e2e00-6153-11ea-9553-155eedf258b7.PNG)
Solved the issue assign me to the task.

**Comment by prateekrai123** [comment]
> Do you want to work on it? If yes, please go on
![image](https://user-images.githubusercontent.com/54741353/76160871-cf84fb00-6153-11ea-9fea-9779c1fee427.png)
Solved it. Assign me to it.

**Comment by abishekvashok** [comment]
Just push in a PR

**Comment by akash-arelli** [comment]
I would like to work on this issue. please assign it to me.
