### ISSUE TITLE
Images need a proper alignment

### ISSUE THREAD

**Issue by tikhsuP** [fossasia/fossasia.org#690]
### Description

The images are aligned to left, by default. This doesn't looks good for screen sizes between 400px to 752px. This needs to be corrected.

![fa](https://user-images.githubusercontent.com/42881874/78145610-b881b200-744e-11ea-937a-94455f245a21.PNG)

![faa](https://user-images.githubusercontent.com/42881874/78145676-cb948200-744e-11ea-8f35-57ca4f6472c6.PNG)

**Comment by tikhsuP** [comment]
We need to assign `margin: auto;` to the images.

**Comment by aman-earthian** [comment]
hey @tikhsuP can I work on this issue.

**Comment by tikhsuP** [comment]
Yes @aman-earthian you are welcome to work on it.
I have tried to simplify the problem and provide a hint to the solution, please feel free to ask any doubts.

**Comment by aman-earthian** [comment]
do i have to commit changes in custom.css file in css folder

**Comment by tikhsuP** [comment]
@aman-earthian 
All you need to do is assign `margin: auto;` to the images that are misaligned.
You can do it in whichever way you like.

**Comment by aman-earthian** [comment]
I have checked by changing through console, every image is assigned image-responsive class and I can set margin-auto by selecting this class, so that's why I am asking is there any standard css file there where all css changes have to be made.

**Comment by Dilshan1997** [comment]
can I work in this issue?

**Comment by Chaitanyassr** [comment]
> can I work in this issue?

@aman-earthian has already submitted a PR which is under review. You can work on a different issue for now. thank you.
