### ISSUE TITLE
"A little more about FOSSASIA" section text Gets Cropped

### ISSUE THREAD

**Issue by ishandeveloper** [fossasia/fossasia.org#692]
![Screenshot (215)](https://user-images.githubusercontent.com/54989142/79631800-c89ccf80-8178-11ea-88d4-bb0ca34d7611.png)

fixed height of the section causes the paragraph text to crop.

**Comment by ishandeveloper** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by Chaitanyassr** [comment]
@ishandeveloper an issue is already there for this..and a professional is also already made..#684. Kindly close this one.
