### ISSUE TITLE
Sidebar Copyright and Misaligned Social Icons

### ISSUE THREAD

**Issue by ishandeveloper** [fossasia/fossasia.org#695]
### Screenshots Of The Issue : 
![image](https://user-images.githubusercontent.com/54989142/80586731-0203f380-8a33-11ea-95a5-0dd84eca39f0.png)

### Proposed Changes :
![image](https://user-images.githubusercontent.com/54989142/80587591-74c19e80-8a34-11ea-8691-37f47a97b1b5.png)

I would like to work on this issue, please assign it to me! 😃

**Comment by Chaitanyassr** [comment]
> ## The copyright text in the sidebar overflows the sidebar area and gets cropped.
> ### Also, the social icons look like they're so tightly squeezed together. I feel that they could use some padding.
> ### Screenshots Of The Issue :
> ![image](https://user-images.githubusercontent.com/54989142/80586731-0203f380-8a33-11ea-95a5-0dd84eca39f0.png)
> 
> ### Proposed Changes :
> ![image](https://user-images.githubusercontent.com/54989142/80587591-74c19e80-8a34-11ea-8691-37f47a97b1b5.png)
> 
> I would like to work on this issue, please assign it to me! 😃

Hi @ishandeveloper thanks for reporting the issue. Go Ahead and make a PR.

**Comment by ishandeveloper** [comment]
Hey @Chaitanyassr I have just created a PR for same. Kindly have a look 😄

**Comment by ishandeveloper** [comment]
@Chaitanyassr Even though the changes were approved, but the PR was stale, while waiting for review since last 20 days. So, it got force-closed by pull-bot.

Can you look into this?
