### ISSUE TITLE
heading overlapped a bit needed a fix

### ISSUE THREAD

**Issue by nlok5923** [fossasia/fossasia.org#701]
![Screenshot_20200508-145854_2](https://user-images.githubusercontent.com/56120084/81393185-bd342880-90d4-11ea-9a17-5a8d838f6951.png)

when viewed via mobile heading overlapped a bit.

can I work on this issue.
please let me know.

**Comment by nlok5923** [comment]
Please can anybody guide me for solving this issue as I am a beginner.

**Comment by Chaitanyassr** [comment]
Hi @nlok5923 thanks for creating the issue. I believe its fine. Instead of this you can focus on fixing and adding the space between OPENTECHSUMMIT and VIETNAM.

**Comment by nlok5923** [comment]
Please can you guide me through which css file I can approach to resolve this issue.

**Comment by nlok5923** [comment]
@Chaitanyassr can you guide me that I should approach which css file to bring necessary changes.

**Comment by nlok5923** [comment]
this issue has been resolved you can view at  vn.opentechsummit.asia and  i had made PR to the github repo 
you can view changes at
https://suspicious-leavitt-4ebe5f.netlify.app/

**Comment by scortier** [comment]
@Chaitanyassr Can i solve this issue.

**Comment by s-pratyush** [comment]
@Chaitanyassr  can i solve this issue

**Comment by Chaitanyassr** [comment]
@nlok5923 Have you opened the iuuse at correct repo? If not then close this issue and opened it in correctt repo and also provide the PR link.
