### ISSUE TITLE
Options in menu are not properly align in a Vertical line in Mobile view

### ISSUE THREAD

**Issue by tewarig** [fossasia/fossasia.org#705]
The which appears in the mobile version of the site, have items not aligned in a  single vertical line.
![WhatsApp Image 2020-05-09 at 17 28 34](https://user-images.githubusercontent.com/54894783/81473236-b3b4d880-921a-11ea-8e77-e7c029a6ab4b.jpeg)
if it is an issue, please tell me I would like to work on it.

**Comment by Chaitanyassr** [comment]
hi @tewarig , thanks for submitting the issue although i believe that its completely fine.

**Comment by tewarig** [comment]
ok, I would be closing the issue.
