### ISSUE TITLE
 Navbar Link is not highlighting on hover in open Tech Summit sri lanka

### ISSUE THREAD

**Issue by keshavagarwal17** [fossasia/fossasia.org#709]
**Actual Behaviour**
Link is not highlighted on hover 

**Expected Behaviour** 
on hover there should be color change of background and text of links.

**Screenshot of issue**
![image](https://user-images.githubusercontent.com/56120769/81532228-ac5c0f00-9381-11ea-8e2d-2ea0dcadccad.png)

**Would you like to work on this issue**
Yes, I would like to work on this issue.Please assign this task to me.

It is not a bug. It is a slight issue with style in links.

**Comment by nlok5923** [comment]
I think this is not the correct repo to raise this issue.

**Comment by Chaitanyassr** [comment]
@The-Keshav-Agarwal Thanks for reporting the issue. Please open it in current repo..and then go ahead and make a PR :)

**Comment by keshavagarwal17** [comment]
ok,thanks.
