### ISSUE TITLE
Background is not visible proper while hover on navigation

### ISSUE THREAD

**Issue by Manish-Kumarr** [fossasia/fossasia.org#710]
### 1.
**----Before Event Hover----**
![before](https://user-images.githubusercontent.com/53834930/81719091-3a2b1d80-949a-11ea-9892-32172dd4a1d2.PNG)

**----After Event Hover----**
![after](https://user-images.githubusercontent.com/53834930/81719100-3e573b00-949a-11ea-89c5-4a150a34b85d.PNG)

### 2.
**----Before Program Hover----**
![before program](https://user-images.githubusercontent.com/53834930/81719136-4911d000-949a-11ea-97bc-2cbf4741756b.PNG)
**----After Program Hover----**
![after program](https://user-images.githubusercontent.com/53834930/81719165-5464fb80-949a-11ea-9c43-6fdde64adf5e.PNG)

### 3.
**----Before About Hover----**
![after about](https://user-images.githubusercontent.com/53834930/81719279-7c545f00-949a-11ea-9ae2-d8366cf57549.PNG)
**----After About Hover----**

![before about](https://user-images.githubusercontent.com/53834930/81719210-621a8100-949a-11ea-89cb-28123de3784b.PNG)

**i want to work on this issue.**

**Comment by Manish-Kumarr** [comment]
@Chaitanyassr Can I work on this issue ?

**Comment by Chaitanyassr** [comment]
Hi @Manish-Kumarr Thanks for reporting the issue. In my case the site is working fine. Backgroud is properly visible in my web browser so i believe that it may be some kind of other problem.

**Comment by Manish-Kumarr** [comment]
@Chaitanyassr if you will keep decreasing your browser then you can see this problem.
