### ISSUE TITLE
licence is not completely visible

### ISSUE THREAD

**Issue by Mayank0022** [fossasia/fossasia.org#711]
It is a issue of styling, licence in the bottom of the sidebar is not completely  visible.

![fossasia_before](https://user-images.githubusercontent.com/57790631/81967950-56b18c00-9639-11ea-94a2-e95015e3025b.jpg)
**before commit**

![fossasia_after](https://user-images.githubusercontent.com/57790631/81968046-79dc3b80-9639-11ea-863b-1a5cb1d068f0.jpg)
**after commit**

**Comment by Mayank0022** [comment]
i would like to work on this issue#711, so please assign it to me.

**Comment by Chaitanyassr** [comment]
Hi @Mayank-create , I similar issue is already there and a PR has also been submitted but you can always work on a different issue.

**Comment by Mayank0022** [comment]
@Chaitanyassr , that's cool

**Comment by chetan-v** [comment]
@Chaitanyassr @Mayank-create  I done this can I send PR

**Comment by Chaitanyassr** [comment]
@chetan no need to solve this issue..there is a PR already there....please work on  a different issue. thank you
