### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by shashwattpandeyy** [fossasia/fossasia.org#713]
Some grammatical error

**Comment by shashwattpandeyy** [comment]
Updated README.md [https://github.com/shashwattpandeyy/fossasia.org.git](url)

**Comment by Chaitanyassr** [comment]
Please also describe the grammatical mistakes.

**Comment by 3scava1i3r** [comment]
Can you please elaborate the issue.

**Comment by Thusal06** [comment]
I checked the README.md and there are no grammatical or any spelling errors in it. But there is a comma missing on 'and' should be corrected as ', and',
![image](https://user-images.githubusercontent.com/66709891/86276019-cbdd1e80-bbf1-11ea-97a1-8f8839c13d19.png)
So, I think the issue has been solved. :)

**Comment by Aaishpra** [comment]
@Thusal06 can i create a pr for this
