### ISSUE TITLE
[Enhancement]: CSS Updation

### ISSUE THREAD

**Issue by sparsh-99** [fossasia/fossasia.org#719]
<b>I suggest that you should use colors in your social media referenced icons to make them more attractive and standardized on hover.</b>

![Screenshot (477)](https://user-images.githubusercontent.com/56729873/82836367-01506700-9ee4-11ea-8e6b-34976a3d29c8.png)
![Screenshot (476)](https://user-images.githubusercontent.com/56729873/82836374-03b2c100-9ee4-11ea-93c6-f68668ca204e.png)

<b>Additional Context</b>
I would also like to add some more CSS typo for better readability of the site.

<b><i>If it possible @Chaitanyassr , I would like to work it all alone</i></b>

**Comment by abishekvashok** [comment]
Hey fossasia uses a standard template for footer across many sites, updating it will require updations to other sites as well. Hence, it is wise to update the footer only when really required. I don't feel the change is necessary. In the meantime, I appreciate the work you've put into looking into this repo, there are more fossasia projects where contributions are needed. Please see them instead :)

**Comment by sparsh-99** [comment]
@abishekvashok But sir, It will look superbly great when icons have its standard colors. I know fossasia set its standard footer but what about I will show my idea through PL and then you would review it. After all, it's all your choice whether to merge it or close it
