### ISSUE TITLE
image responsive issue in mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/fossasia.org#735]
![issue 1](https://user-images.githubusercontent.com/65535360/86438897-08f5fd80-bd25-11ea-990a-6c7917fa92b5.PNG)

Image responsive issue in mobile view see in the screenshot for the better understanding.....

**Comment by Adhinesh-Reddy** [comment]
> ![issue 1](https://user-images.githubusercontent.com/65535360/86438897-08f5fd80-bd25-11ea-990a-6c7917fa92b5.PNG)
> 
> Image responsive issue in mobile view see in the screenshot for the better understanding.....



![IMG_20200720_160117](https://user-images.githubusercontent.com/68197578/87929287-d299db80-caa3-11ea-8d24-9f8eab97c4b3.jpg)


I have adjusted the image.
If liked it then please let me know.

**Comment by Adhinesh-Reddy** [comment]
I want to do.

**Comment by Raunaksingh100** [comment]
@Adhinesh-Reddy  go ahead...

**Comment by khushishikhu** [comment]
may i work on this issue?

**Comment by Abhigyankrsingh** [comment]
Sir, I will work on this because it is an open issue and so i will do Sir.
