### ISSUE TITLE
Copyright issue not solved yet!! footer problem

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/fossasia.org#742]
![footer issue](https://user-images.githubusercontent.com/65535360/86509434-85600d80-be05-11ea-93e3-30d14ef7f796.PNG)

**Comment by Raunaksingh100** [comment]
@endhambot not fixed yet see in the offical website

**Comment by Dilshan1997** [comment]
I working this issue

**Comment by Raunaksingh100** [comment]
@dilshan1997

Already My  pr for this and it is approved by mentors

**Comment by liveHarshit** [comment]
Merged
