### ISSUE TITLE
Bottom to top button alignment issues.

### ISSUE THREAD

**Issue by Neilblaze** [fossasia/fossasia.org#758]
• Issue :-

In the landing page of Fossasia i.e fossasia.org, the Back to top button is not correctly aligned, & when page is zoomed in (>125%), it gets out of page margin.

![b2t](https://user-images.githubusercontent.com/48355572/87326535-7d644400-c550-11ea-99fb-466af9ab03bc.JPG)

• Do I want to work upon this issue?

Yes, I want to work upon this issue. It would be better if the existing "Bottom to top" button be replaced with that of that in this page `https://blog.fossasia.org/contact/`

**Comment by bankebihariagrawal** [comment]
can I work on this?

**Comment by bankebihariagrawal** [comment]
After the changes, it looks like this

![Bottom button](https://user-images.githubusercontent.com/52813916/87415669-0cbe3580-c5eb-11ea-80b3-602604238a95.png)

**Comment by bankebihariagrawal** [comment]
Can I made a pull request?

**Comment by Neilblaze** [comment]
@bankebihariagrawal I already mentioned that I was working on it :)

**Comment by bankebihariagrawal** [comment]
Ok

**Comment by tarunsinghofficial** [comment]
Can I work on it?

**Comment by Neilblaze** [comment]
@tarunsinghofficial there's already a PR issued to this issue - #759
