### ISSUE TITLE
The Names of the Android apps name not visible (BUG)

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/fossasia.org#760]
The name of the Android apps is not visible  see the screenshot for the better understanding

!screenshot --------

![foss](https://user-images.githubusercontent.com/65535360/87847808-72b30180-c8f8-11ea-9a45-5010e9b30277.PNG)

**Comment by agarwalraj505** [comment]
I want to work on this issue please assign me this task. Also, I am new to this repository so do help me to navigate through the repository.

**Comment by Raunaksingh100** [comment]
@agarwalraj505  you can work on this issue just 
do fork then clone..

**Comment by agarwalraj505** [comment]
OK

**Comment by Dilshan1997** [comment]
I can fix this issue

**Comment by Dilshan1997** [comment]
#765 
problem fix
![change app name design](https://user-images.githubusercontent.com/48722230/89671929-7cc98e00-d901-11ea-8567-b68be485c4b9.PNG)
