### ISSUE TITLE
Footer inside "hamburger" menu and "back to top" arrow button is very  narrow and small

### ISSUE THREAD

**Issue by kmlhsn** [fossasia/fossasia.org#782]
Description:

Footer inside hamburger menu and "back to top" arrow button is very  narrow and small

expectation:

footer should be on the bottom of the page and  "back to top" arrow button should be good look
Step top reproduce:

1. Go to https://fossasia.org/
2. Click on the "hamburger" menu
3. Scroll down to bottom

![image](https://user-images.githubusercontent.com/32615215/91882211-7631fa80-eca4-11ea-9a5b-1cf0978bc7e9.png)

**Comment by Utkarshn10** [comment]
I am a beginner and I would like to work on this issue. And will try my level best to fix it.

**Comment by Raunaksingh100** [comment]
@kmlhsn there is no issue in footer size ..

**Comment by kmlhsn** [comment]
"back to top" arrow button is not in correct design

**Comment by Raunaksingh100** [comment]
> "back to top" arrow button is not in correct design
I only said that there is no issue in footer 
Because the layout and size of footer I fixed in previous months

**Comment by Raunaksingh100** [comment]
> "back to top" arrow button is not in correct design

This issue is duplicate and there is already pr for this here the link of pr-
#759

You can closed this issue....
