### ISSUE TITLE
  homepage design breaks when "hamburger" menu appears

### ISSUE THREAD

**Issue by kmlhsn** [fossasia/fossasia.org#783]
Description:

homepage design breaks when "hamburger" menu appears

expectation:

homepage design should not break when "hamburger" menu appears. Design should always fixed

Step top reproduce:

   1. Go to https://fossasia.org/
   2. Click on the "hamburger" menu
![image](https://user-images.githubusercontent.com/32615215/91884787-7d5b0780-eca8-11ea-9417-46b77f3754c9.png)

**Comment by mariobehling** [comment]
This works as intended
