### ISSUE TITLE
Entire article shown on front page of the Blog

### ISSUE THREAD

**Issue by kmlhsn** [fossasia/fossasia.org#784]
Description:

Almost entire article is being shown on the front page of the blog

Expectation:
 Only "Title/Head Line", "featured Image" and Summery of the article should be displayed on front page

step to reproduce:
1. Go to http://fossasia.org/
2. Click on "Blog"

![image](https://user-images.githubusercontent.com/32615215/91886137-b6947700-ecaa-11ea-8b05-fac47928ea89.png)

**Comment by hp77-creator** [comment]
@mariobehling  I visited blog and was able to reproduce this issue. I thought there might be some error in ./js/blog.js maybe something in feednami API or something similar of sort but there was no fault as such. Then I inspected the webpage and there I couldn't find any script tag which sources blog.js, so I am finding error at the wrong place. Can you guide me where to look at to solve this one. I think I can do it. Thanks.

**Comment by mariobehling** [comment]
This is working as intended. Thanks.
