### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by sagar-barapatre** [fossasia/fossasia.org#788]
Save our eyes. And batteries. Do not ignore this property of useragent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by Deepaliiii** [comment]
i want to work on this . 
may i ?

**Comment by khushboojoshi3** [comment]
Can I work on this issue? Please assign me this issue.

**Comment by sagar-barapatre** [comment]
Look I am not the owner of this repo, so i can't assign anyone. SORRY for that
But i strongly recommend you both to start working on this issue and make a PR.

**Comment by Raunaksingh100** [comment]
> Look I am not the owner of this repo, so i can't assign anyone. SORRY for that
> But i strongly recommend you both to start working on this issue and make a PR.

no only one person can work on an issue , because it lead to duplicate Work

**Comment by rajitha302** [comment]
Is there anyone who's actively working on this issue?

**Comment by Raunaksingh100** [comment]
> Is there anyone who's actively working on this issue?

No go ahead !!
