### ISSUE TITLE
idea can added svg animation on hovering on social media icons

### ISSUE THREAD

**Issue by harkiratsm** [fossasia/fossasia.org#826]
please lemme know i have the ideas it would looking great do lemme know that should i start working on this(on -mouse hovering)
![lop](https://user-images.githubusercontent.com/71957674/113538994-4cee9980-95fa-11eb-9bec-747fc834dcfd.gif)

**Comment by Rara1410** [comment]
I like to work on it can please provide me the link to the animated gifs

**Comment by Rara1410** [comment]
or any kind of guide for the icons

**Comment by Rara1410** [comment]
@harkiratsm  hii sir can I work
