### ISSUE TITLE
icon not showing 

### ISSUE THREAD

**Issue by ayushnau** [fossasia/fossasia.org#835]
![fossasiaerror](https://user-images.githubusercontent.com/78146753/129031807-fefdf64e-cbfd-427e-b55d-3b90d7ea5215.png)

**Comment by SamarthAroraa** [comment]
Hi, @Ayush2020012016 I was not able to reproduce the issue. Could you include steps to reproduce the issue?

**Comment by imthegithubuser** [comment]
can i work on this issue?

**Comment by abishekvashok** [comment]
Closing as not reproducable
