### ISSUE TITLE
web-page can be Enhanced: can implement a horizontal transparent menu-bar

### ISSUE THREAD

**Issue by Tikam02** [fossasia/fossasia.org#85]
Actually in http://fossasia.org website when menu bar is clicked the page moved to left side:Like this
![foss-page](https://cloud.githubusercontent.com/assets/10548085/21253773/0f6bacdc-c387-11e6-9847-aea6852c8744.png)
![foss-page1](https://cloud.githubusercontent.com/assets/10548085/21253784/1d4d1066-c387-11e6-935c-e2ae00d94b14.png)
we can do is just make a simple horizontal menu-bar and which will show all the social icons:and not affect the page.
sir can contribute to this issue.

**Comment by mariobehling** [comment]
Thanks. This is out of scope at the moment. Would be great, if you help with other issues though. Right now we need help with the open event orga server: https://github.com/fossasia/open-event-orga-server
