### ISSUE TITLE
Pin versions of Python modules.

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/fossasia.org#86]
@AmazingAbdullah We will need another commit to make travis run. Can you do the following?

Pronblem: With Python you can not be sure which version you get when you do `pip install packageX`. Zou would usually do `pip install packageX==VERSION` for the version that works.

Solution: Add the version information to allow future compatibility even several years in the future.

**Comment by AmazingAbdullah** [comment]
Got it!

**Comment by AmazingAbdullah** [comment]
I submitted the pull request #87 @niccokunzmann

**Comment by niccokunzmann** [comment]
Thanks, you resolved this.
