### ISSUE TITLE
Join fossasia link

### ISSUE THREAD

**Issue by m1guelpf** [fossasia/fossasia.org#92]
Hi!

I've noticed the normal behaviour on joining fossasia is that the user asks an admin/completes the form and waits for approval.
I've created a tool called OrgManager that allows you to generate links to join a Github organization!
(You may want to get more info at [the github repo](https://github.com/m1guelpf/orgmanager) or [see it in action](https://orgmanager.miguelpiedrafita.com).)

Some organizations like [Open Source Design](https://github.com/opensourcedesign) are using it to make joining faster!

It even has an API, if you want to integrate it with your application!
([Api docs](http://docs.orgmanager.miguelpiedrafita.com))

What do you think?

PD. If you think it could have other nice features, just [open an issue on the repo](https://github.com/m1guelpf/orgmanager/issues/new?labels=suggestion&title=Awesome%20new%20feature%20for%20OrgManager!)!

**Comment by jitendra3109** [comment]
> First, I didn't know where to open this, as fossasia doesn't have any "organization" repos.

What do mean by that?
You are the member of it.
Without approval how can people join Org.

**Comment by m1guelpf** [comment]
@jsroyal I meant that people normally have to wait for manual approval when joining FOSSASIA, and providing a solution.

**Comment by jitendra3109** [comment]
@m1guelpf I agree on that need to manual approval take time.So what are the criteria for joining the org in your solution? 
Is that only GitHub login?

**Comment by m1guelpf** [comment]
@jsroyal OrgManager is an application that uses the Github API to instantly invite new users to the organization. The users don't have to login, they only write their username and fill a captcha, and Organizations can optionally protect signups by requesting a password. Also, an API is available so Organizations can build custom integrations.

**Comment by mariobehling** [comment]
@m1guelpf OrgmManager is a nice idea, but the sign up page asks me for admin access to all my organizations. 

Firstly, why do I need to give admin access. Isn't there a way to give less access rights?

Secondly, why do I need to provide admin access to all my organizations?

![screenshot from 2017-03-05 10-28-33](https://cloud.githubusercontent.com/assets/1583873/23583989/e8d67d04-018e-11e7-8173-5e95f8265ca3.png)

**Comment by m1guelpf** [comment]
@mariobehling Admin access in needed to use the invites API. Also, FOSSASIA (and maybe your other organizations) is not configured correctly, and auto-authorizes every request. You may want to check the help page of GitHub for this: https://help.github.com/articles/about-third-party-application-restrictions/

**Comment by m1guelpf** [comment]
@mariobehling Any updates?

**Comment by mariobehling** [comment]
@m1guelpf I have finally worked it out now. Here it is https://orgmanager.miguelpiedrafita.com/o/fossasia. Would be great to get a code snippet for a popup for the website here. So people don't have to leave the site.

**Comment by m1guelpf** [comment]
@mariobehling I am woking on a link that authorizes the user and then redirects back to the organization page. Will notify you when it's ready. You can also use the OrgManager REST API if you want.

**Comment by abishekvashok** [comment]
@m1geulpf https://orgmanager.miguelpiedrafita.com/o/fossasia is working now,a re we done with this issue?

**Comment by m1guelpf** [comment]
@abishekvashok Yeah, it's done now.

**Comment by rubiin** [comment]
Any updates on this. Cannot seem to join
