### ISSUE TITLE
Tweet Section no longer providing tweets from loklak

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#96]
Tweet section is supposed to show tweets.

**Comment by dilpreetsio** [comment]
@mariobehling Do we only have to show tweets and not retweets from FOSSASIA ?
Tweets older than 1 month wont be displayed as loklak now only stores the tweets that are no older than one month. The tweet section wont populate as there has been no tweets for fossasia within last month.

**Comment by mariobehling** [comment]
Tweets and Retweets, please.

> Tweets older than 1 month wont be displayed

No need to repeat this everywhere. I am the one who did this with Michael.

**Comment by dilpreetsio** [comment]
Sorry, I was just trying to clear things. Thanks

**Comment by mariobehling** [comment]
Thanks for the changes. Tweet days are wrong though. Issue here https://github.com/fossasia/fossasia.org/issues/98

Any ideas?
