### ISSUE TITLE
Wrong date on tweets

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia.org#98]
Tweets are showing wrong post date, e.g. 0 days ago for tweets that are posted long ago.

![screenshot from 2017-05-01 23-50-48](https://cloud.githubusercontent.com/assets/1583873/25596392/33ae6ed8-2ec9-11e7-95bb-e23273d873ed.png)

**Comment by dilpreetsio** [comment]
@mariobehling I have checked and closely monitored the tweets and the dates displayed, it seems that the dates of the tweets are correct for the tweets older than 24 hours. For tweets which were posted within 24 hours are displayed as `Tweeted 1 days ago`. I was not able to find any tweets with `Tweeted 0 days ago`, Can you please give any example of such case?

**Comment by mariobehling** [comment]
Closing in favor of https://github.com/fossasia/fossasia.org/issues/149
